### ISSUE TITLE
Documentation for 0.7 says that it depends on pandas==0.23.4, but when I import modin it says it requires pandas==0.25

### ISSUE THREAD

**Issue by KevOBrien** [modin-project/modin#1046]
In the [modin documentation for 0.7]( https://modin.readthedocs.io/en/latest/installation.html#dependencies), it says that it depends on `pandas==0.23.4`, but when I install `modin==0.7` and try to import it, the following import error is thrown:

    ImportError: The pandas version installed does not match the required pandas version in Modin. Please install pandas 0.25.3 to use Modin.

Is this an error in the documentation? Is there anyway I can use `modin==0.7` with `pandas==0.23.4` as I am using Dataiku DSS v6.0, which requires `pandas==0.23.4` and cannot be upgraded.

**Comment by devin-petersohn** [comment]
Hi @KevOBrien, this is a typo in the documentation. The pandas API has changed some since the 0.23 release, and as of right now there's no way to ignore the pinned version.

The reason for the pin is that we can only guarantee API identity on a single version, so we choose the latest. Since pandas release 1.0 last week, I still need to update it within Modin.

I suppose I could create a workaround for the pandas version. We don't have the manpower to support all pandas versions in the same way, so might be some issues that pop up with older versions. Either way I need to update the documentation to be up to date. Let me know if you have any opinion.

**Comment by KevOBrien** [comment]
What sort of workaround for the pandas version do you have in mind? It would be great if I could run modin 0.6 or 0.7 with pandas 0.23, and I would fully understand that there is a risk of incompatability issues, which I would have to test for myself

**Comment by devin-petersohn** [comment]
I could just give a warning instead of throwing an exception. That way you could use it at your own risk without any changes in your behavior.

**Comment by KevOBrien** [comment]
Yes that would be great. Thank you
