### ISSUE TITLE
Refactoring GroupBy

### ISSUE THREAD

**Issue by magnatelee** [modin-project/modin#1062]
### Describe the problem

Currently, there is no way for a backend to tell which aggregation the program requested with a GroupBy, as the aggregation function is passed in as an opaque Python function. This doesn't work for backends that are trying to provide specialized implementations for aggregation, and the backend should at least know the name of the aggregation.

### Source code / logs
https://github.com/modin-project/modin/blob/master/modin/pandas/groupby.py#L162
https://github.com/modin-project/modin/blob/master/modin/pandas/groupby.py#L482

**Comment by devin-petersohn** [comment]
Thanks @magnatelee, we should put some thought into the design because we don't want to blow up the `query_compiler` API. Maybe we can reuse some of the existing API, e.g. `count` can accept a `groupby` as well.

The `groupby` functionality is wildly inconsistent between operators, so we're going to have to think through handling the edge cases as well.
