### ISSUE TITLE
Semantic version check fails for Dask/Distributed versions

### ISSUE THREAD

**Issue by jkeane** [modin-project/modin#1093]
### System information
- **Windows x64**:
- **Modin installed from binary**:
- **Modin 0.6.3**:
- **Python 3.7**:
- **import modin.pandas as pd**:

### Describe the problem
The technique for semantic version checking cannot use string comparison.  e.g. 2.11.0 is semantically greater than 2.3.0 but fails if you use a string comparison: '2.11.0' < '2.3.0'

### Source code / logs
Line 54-55 should read:
`
                    list(map(int, dask.__version__.split('.'))) < [2,1,0]
                    or list(map(int, distributed.__version__.split('.'))) < [2,3,2]
`

**Comment by devin-petersohn** [comment]
Thanks for the report @jkeane, this was recently fixed in #1050. I'm releasing within the next few days, so it will be reflected in the next release.

As a temporary workaround, you can set the environment variable `MODIN_ENGINE=dask` (in python via `import os; os.environ["MODIN_ENGINE"] = "dask"`) and it will bypass any of those checks. You can also build from master: https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch

I'm closing since this was already fixed, but feel free to continue commenting/reopen if it's still broken for you on master.
