### ISSUE TITLE
the speed is almost same when using different number of cpu

### ISSUE THREAD

**Issue by franknerd** [modin-project/modin#1111]
I am trying to figure out how Modin use cpus and make a comparison between Pandas and Modin.

So I did some tests by loading  1 GB dataset.
I almost spend the same amount of time when using different number of CPU on Modin.
However, there is a big difference between using 1 cpu on Modin and just using Pandas.

Hi Gurus here, may I know the reason behind it? Thank you

```
from distributed import Client
client = Client(n_workers=1)
import modin.pandas as pd
import time

start_time = time.time()
df = pd.read_csv('file.csv')
print(time.time()-start_time)
```

**Comment by devin-petersohn** [comment]
Hi @franknerd thanks for the question! This is a great question.

To parallelize the computation and use more CPU cores, we partition the data between workers (CPUs). There is an overhead to managing partitioning and the metadata (index, columns, data types) when the data is split up and cannot be easily shared. Sometimes this overhead is minimal or we can be even more efficient than pandas. We have spent a lot of time optimizing `read_csv` because we found that to dominate runtime in many cases for users.

We have a minimum number of partitions for larger datasets. We still split the data, even if there are fewer CPUs because it can be more efficient in many cases in pandas to manage many small dataframe chunks rather than one large dataframe. There are also many examples in the API where this is not true, of course.

With parallelism, there's always an upper limit to the best performance you can get. There's still a lot of exciting things we will do in the future with performance improvements and optimization. For now, we're mostly using basic parallelism to improve the performance.

If you'd like to play around with partitioning performance, you can modify `pd.DEFAULT_NPARTITIONS` to change the default number of partitions, currently set to a minimum of 4. I don't recommend this for average users during their workflows because it will dramatically change the performance in some cases.

```python
import modin.pandas as pd
pd.DEFAULT_NPARTITIONS = 1
pd.read_csv(...)
```

This will change the partitioning as well to a single large partition (if you'd like another knob to play with).

**Comment by sidazhou** [comment]
I got 40 cores to read 70G file. I see only 1 core has 100% utilization, and rest 39 cores hovers around 4%. 

When I do `pd.read_csv()`, the result is `modin.pandas` is only around 20% faster than `pandas`. Is this expected normal behavior?

**Comment by devin-petersohn** [comment]
@sidazhou Thanks for the question, but it is not related to this particular thread. This thread is about why Modin takes the same amount of time on different CPU configurations. I would like to help debug your issue, so please open a new issue so this topic does not get changed.

**Comment by mvashishtha** [comment]
I'm closing this issue as stale. @franknerd please let us know if we need to address anything else.
