### ISSUE TITLE
df.groupby('Col') falls back to Pandas claiming I'm attempting multi-column groupby

### ISSUE THREAD

**Issue by formigone** [modin-project/modin#1114]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOSX 10.15.2
- **Modin version** (`modin.__version__`): 0.7.1
- **Python version**: 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
- **Code we can use to reproduce**:

```python
import glob
import modin.pandas as pd

df = pd.DataFrame()
for file in glob.glob('data/*.csv'):
    df = pd.concat([df, pd.read_csv(file)])

df.shape
# (98471725, 5)

df.loc[:, 'Prev'] = df.groupby('Session').Template.shift()
```

### Describe the problem

Attempting a simple `df.groupby('col')` defaults to Pandas claiming that I'm attempting to group by on multiple columns. Maybe this is a vocabulary thing. But sounds like Modin is confused about what I'm requesting on that groupby?

![image](https://user-images.githubusercontent.com/852234/75416600-e7ef4d00-58eb-11ea-9fd9-b746a8a6821d.png)

**Comment by devin-petersohn** [comment]
Hi @formigone, thanks for the report!

This is a bad error message, we lump a bunch of error messages related to groupby under the same error message. Because of how error messages work in the groupby code, everything not implemented throws that same message. We should be more clear here. The thing we haven't implemented yet is the `SeriesGroupBy` which is the `.Template` part of your code. We have plans to implement this soon, and I've already mocked up an implementation that hasn't been fully tested.

Side note unrelated to the issue, I recommend rewriting the `read_csv` and `concat` parts like this:

```python
df = pd.concat([pd.read_csv(f) for f in glob.glob("data/*.csv")])
```

For both pandas and Modin this should be faster because there are overheads to calling `concat` multiple times and `concat` allows you to pass the whole list of objects. We try to minimize these overheads as much as possible but they're still there.

**Comment by devin-petersohn** [comment]
Changing this to New Feature because I would rather implement this than fix the error message 😄
