### ISSUE TITLE
Standardize project file line endings

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#1157]
Due to contributors working on this project cross platform, we have some files that use CRLF and some that use LF. We should standardize to LF for all files and ensure that in the future, updates to files and new files have LF only.

**Comment by gshimansky** [comment]
I suggest that we add a `.gitattributes` file for the repository and specify `auto` setting for all text file. This will make git to checkout automatically based on platform that it runs on. On Unix git would automatically check out files with LF line endings, on Windows CRLF. In addition we could add a test similar to file headers test that would check that no CRLFs are present in any source text file, since all our tests run on Linux, they should have no `0x0D 0x0A` byte sequences present.

**Comment by devin-petersohn** [comment]
Alternatively, we could set `.gitattributes` to only allow commits with `lf` as the following:

```
*.py text eol=lf
...
```

This would ensure that the line endings were what we want and we don't have to worry about moving between OS and running `dos2unix`. I agree we should also add this formatting line test.

**Comment by gshimansky** [comment]
With `eol=lf` files are checked out with Unix line endings even on windows which may impact some users who use dumb text editors on windows. But it could be a small minority.

**Comment by devin-petersohn** [comment]
I see the problem, I agree with `text=auto` and a test.
