### ISSUE TITLE
DataFrame unable to apply a function that calling itself

### ISSUE THREAD

**Issue by Michany** [modin-project/modin#1173]
### System information
- **OS Platform and Distribution**: Windows 10 1909
- **Modin version** (`modin.__version__`): 0.7.2
- **Python version**: 3.7.4, Pandas Version: 1.0.1
- **Code we can use to reproduce**:

```py
df.timeoffset.apply(lambda x:df.index.slice_indexer(x,x+60))
```
Literally the `df` looks like this, where `df.index` is the same as `df.timeoffset`

  | timeoffset | data | data | data
-- | -- | -- | -- | --
5400  | 5400 | 29200 | 29.25 | 4600
5403  | 5403 | 93900 | 29.27 | 400
5406  | 5406 | 2200 | 29.24 | 1100
.. | ...   . | ... | ... | ...
25005 | 25005 | 15500 | 29.57 | 7700
25008 | 25008 | 15500 | 29.61 | 9400
25011 | 25011 | 11500 | 29.61 | 14400

### Describe the problem

I'm trying to create some rolling windows according to `df.timeoffset`, and obtain the index of these rolling windows.

But it won't work except giving me the following log output.

### Source code / logs

```
UserWarning: `DataFrame.__getstate__` defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
...(Won't stop until I manually interrupt it)
```

I'm think there's nothing wrong with `df.index.slice_indexer` or `df.apply`,
So I guess the problem is that, the `df` itself was called again within the apply lambda function.

**Comment by Michany** [comment]
BTW, the Modin implementation of  `pd.read_table()` function is really nice, reducing the running time by 65% on i7-9750h (6 cores). 
Thanks for creating this wonderful toolkit.

**Comment by devin-petersohn** [comment]
Hi @Michany, thanks for the report.

The problem here is that accessing the `df` from within the `apply` function is attempting to pickle the entire dataframe, which isn't supported (#672). We do plan on allowing this, but there are challenges with allowing each partition to interact with the entire dataframe. This is where the `__getstate__` comes in.

One workaround for your case using functionality that is implemented (until we can get the functionality you need implemented):

```python
df[["timeoffset"]].apply(lambda x: x.apply(lambda z: x.index.slice_indexer(z, z+60))).squeeze()
```

Since you only need the index values, we can use the `DataFrame.apply` method to call the `Series.apply`. It'll unfortunately have limited parallelism, but it will be better than defaulting to pandas or throwing an error. `apply` is very challenging, and we are constantly iterating on it. `pandas` allows nearly unbounded functions to be passed in, so we are constantly trying to improve. The next step is inspecting the user's function and calculating parallelism and optimization based on that. That will take some time to implement and test.

**Comment by Michany** [comment]
Thanks, this actually works! Hope to see more features coming.
