### ISSUE TITLE
pivot function implementation

### ISSUE THREAD

**Issue by aregm** [modin-project/modin#1201]

**Comment by dchigarev** [comment]
**Current state:**
`pivot` is one of the reshape methods that have design documentation. However, implementation with the following of design caused unexpected performance issue that explained in details in [this comment](https://github.com/modin-project/modin/pull/1645#issuecomment-661304093), in a few words - it's because of extremely large input of reduce function at the second phase of `groupby_reduce`.

There is another implementation, that uses draft implementation of `unstack` from #1649, which performs significantly better. For now which implementation to use is under discussion. Both implementation could be found at #1645.
