### ISSUE TITLE
Incorrect dtype when DataFrame is distributed

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1412]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Windows 10

- **Modin version** (`modin.__version__`):

0.7.2+85.gb9b791f.dirty

- **Python version**:

Python 3.7.7

- **Code we can use to reproduce**:

```python
if __name__ == "__main__":
    import numpy as np
    import modin.pandas as pd

    s1 = pd.DataFrame(np.arange(1, 10000, dtype=np.float32), columns=["s1"])
    print(s1.dtypes['s1'])
```

### Describe the problem

On Modin resulting dtype is `float64` while on Pandas it is `float32`.

**Comment by devin-petersohn** [comment]
Interesting, it appears that it does not happen when data is loaded with `dtype` kwarg.

**Comment by dchigarev** [comment]
There is a bug in DataFrame constructor:
https://github.com/modin-project/modin/blob/4c772ab5a97276709ae9e035ead5198caaa7f2bf/modin/pandas/dataframe.py#L113-L116
That list comprehension expression will return a python `list` with no `dtype`, with elements of `data`.
Let's say our `data` is `np.ndarray` with `dtype=float32`, after above expression, we will get a list of array elements, and then, when we would like to create `pandas.DataFrame`:
https://github.com/modin-project/modin/blob/4c772ab5a97276709ae9e035ead5198caaa7f2bf/modin/pandas/dataframe.py#L124-L127
Pandas will automatically detect the `dtype` as `float64`, because it has no information about original data type.
