### ISSUE TITLE
Assignment to DataFrame[column][row] does not work

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1429]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 19.10

- **Modin version** (`modin.__version__`):

0.7.3+15.gc09e61f.dirty

- **Python version**:

Python 3.7.5

- **Code we can use to reproduce**:

```python
import pandas as pd
import modin.pandas as mpd

pdf = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
                   index=[0, 1, 2],
                   columns=['index', 'shield'])
mdf = mpd.DataFrame([[1, 2], [4, 5], [7, 8]],
                    index=[0, 1, 2],
                    columns=['index', 'shield'])

print(pdf['index'][0])
print(mdf['index'][0])

pdf['index'][0] = 1000
mdf['index'][0] = 1000

print(pdf['index'][0])
print(mdf['index'][0])
```

### Describe the problem

When assignment is done to `DataFrame[column][row]` in Modin it has no effect. I think assignment is done to a copy of `DataFrame[column]` while the original contents of `DataFrame[column]` is not changed. It is possible to write assignment like this: `col = DataFrame[column]; col[row] = value; DataFrame[column] = col` and this works, but plain assignment to `DataFrame[column][row]` doesn't work as expected.

**Comment by devin-petersohn** [comment]
@gshimansky This is likely because the `__setitem__` in the `Series` is not propagating back to the `_parent` field. `Series` should have a `_parent` if it came from a `DataFrame`.

**Comment by gshimansky** [comment]
@devin-petersohn I implemented propagation in #1434 in a simple way just assigning `self` to `self._parent[self.name]`. I am not sure whether it is a correct what because before this assignment `self` and `self._parent[self.name]` are two different Series, they are different objects. Assignment makes `_parent` to refer to `self` and discards a copy that was present in parent dataframe.
Is it ok to do this or should be copy contents of `self` into `self._parent[self.name]` and keep two Series objects separate?

**Comment by devin-petersohn** [comment]
Yes, this is a complicated behavior for a couple of reasons. In short, we should be overwriting the original Series in the parent DataFrame.

The pandas behavior is to overwrite because we have a "view" instead of a copy, where when we edit the `df["column"]`, it is manipulating the memory of the underlying structure. This is problematic for a number of reasons, but we have a functional underlying structure, so an operation always returns a new Modin query compiler.

If a copy is created, i.e. `s = df["column"].copy()`, the original will stay around, otherwise it will eventually be garbage collected.

**Comment by gshimansky** [comment]
Ok thanks. Then my change in #1434 is correct.
