### ISSUE TITLE
Series.reset_index does not consider 'name' parameter

### ISSUE THREAD

**Issue by isilopekel** [modin-project/modin#1457]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **Modin version** : 0.7.3
- **Python version**: 3.6.7
- **Code we can use to reproduce**:
```
Create dummy.csv with following content: 
a,b,c,
1,2,3
4,5,6

if __name__ == "__main__":
    import modin.pandas as mpd
    df=mpd.read_csv("dummy.csv", sep=",")
    df_count = df.groupby(["a", "b"]).size().reset_index(name="Count")
    print(df_count.columns)

    import pandas as pd
    df=pd.read_csv("dummy.csv", sep=",")
    df_count = df.groupby(["a", "b"]).size().reset_index(name="Count")
    print(df_count.columns)
```
### Describe the problem
Multi-column grouping loses the column names. Output of the code snippet:
Index(['level_0', 'level_1', 'Count'], dtype='object')
Index(['a', 'b', 'Count'], dtype='object')

**Comment by devin-petersohn** [comment]
Hi @isilopekel thanks for the report!

This issue is due to `groupby.size` not being implemented. We have a start on this, it will be in the next release.

Normally we would return a `modin.pandas.Series`, but this will return a `pandas.Series` object because it is very old code from before the `Series` implementation.

Link to `groupby.size` implementation: https://github.com/modin-project/modin/blob/985adb019e8586b2d666eebc1888c68e4035e8b7/modin/pandas/groupby.py#L365-L366

**Comment by dchigarev** [comment]
It seems that the problem here is not in groupby at all, but in `reset_index`. It seems that it does not consider custom `name`
```
if __name__ == "__main__":
    import pandas
    import modin.pandas as pd
    
    md_sr, pd_sr = pd.Series([1, 2, 3, 4]), pandas.Series([1, 2, 3, 4])

    print(md_sr.reset_index(name="Custom name").columns) # Index(['index', 0], dtype='object')
    print(pd_sr.reset_index(name="Custom name").columns) # Index(['index', 'Custom name'], dtype='object')
```

**Comment by devin-petersohn** [comment]
@dchigarev Great find! Please change the title of the issue to reflect the correct issue.
