### ISSUE TITLE
Compare Ray cloud scaling vs Enzyme approach

### ISSUE THREAD

**Issue by aregm** [modin-project/modin#1482]
Ray has some naive approach for scaling in the cloud. Need to compare with Enzyme approach/functionality.

**Comment by anmyachev** [comment]
Technical solutions | Ray   autoscaler (by default) | Enzyme
-- | -- | --
Incoming traffic | To any   node using the ssh protocol on port 22.   (see   `_configure_security_group`) | Only to the head   node by any protocol.   (see `aws_security_group`)
Outgoing   traffic | Not regulated.   Everything is   allowed. | Only from the head   node according to any protocol.    (see `aws_security_group`)
Interaction   with cloud providers | Used next SDKs: boto3, googleapiclient … | Used next tools:       terraform, packer
Subnet   creation | Only   by hand.   (see   `_configure_subnet`) | Automatically.   (see `aws_subnet`)
Public IP | Subnet   dependent. If the option to automatically assign public IP addresses (when   creating a subnet) is enabled, then public IPs are assigned to every node.   Otherwise, only private ones are   assigned.   (see   `_configure_subnet`) | The public   address is assigned only to the head node.
Cluster size | Dynamic.   (see   `target_utilization_fraction`) | Static
Configuration file   format | toml/yml | json
SPOT instances | Used   for worker nodes | Not used
Socks Proxy | Not   supported | Supported only by   Packer
Credentials | Defined   via environment variables | Defined via   credential file
Cluster creation | The   head node is created from the local desktop.   Worker nodes are   created from head node. | Head and worker   nodes are created from the local desktop
Auto cluster   remove | Supported | Not supported

**Comment by anmyachev** [comment]
The table was added into internal wiki page. (modin channel)
