### ISSUE TITLE
using .iloc to assign new value

### ISSUE THREAD

**Issue by ndy-cd** [modin-project/modin#1556]
#### System information
- **Linux Ubuntu 19.10**
- **Modin 0.7.3**
- **Python 3.7.7**

#### Problem:
When trying to use .iloc to assign a new value there are no changes taking place.

I already left a comment on the issue #147 but it's already closed and I wasn't sure that you can see it.

#### Code to reproduce:
```
import modin.pandas as pd #dask
test = pd.DataFrame({'first': range(10)})
test['first'].iloc[0] = 500
#or test['first'].iloc[[0, 1, 2]] = 500
print(test) # there is no changes
```

**Comment by devin-petersohn** [comment]
Thanks @ndy-cd, we prefer the new issue since the old one was resolved. This issue is slightly different because of the assignment.

So what is happening is that the `test['first'].iloc` assignment is happening inplace in pandas. Modin is doing the assignment, but not propagating the `test['first']` back to the original dataframe. It will be straightforward to fix, the two types of indexing case in the same statement (`first`, and `iloc`) was not handled.

Assignment with `loc`/`iloc` will work if you don't access the column first. A simple temporary workaround for the double indexing is to turn it into a single `loc` call:

```python
import modin.pandas as pd #dask
test = pd.DataFrame({'first': range(10)})
test.loc[0, 'first'] = 500  # 0 is the Index value of the 0th row
#or test.iloc[[0, 1, 2], 'first'] = 500
print(test)
```

If you prefer to use `iloc` you can also do this:

```python
import modin.pandas as pd #dask
test = pd.DataFrame({'first': range(10)})
test.iloc[0, 0] = 500  # 0 is the column and row number
#or test.iloc[[0, 1, 2], 0] = 500
print(test)
```

We have the machinery in place to support this, but it looks like something got lost with the double indexing. Thanks for the detailed report! We will get this fixed.

**Comment by ndy-cd** [comment]
Thank you very much for detailed answer!

It seems to be a same problem with using .replace()
`test['first'].replace({500: 40}, inplace=True)`
