### ISSUE TITLE
2D assignments in `loc/iloc` are broken

### ISSUE THREAD

**Issue by YZ576023775** [modin-project/modin#1620]
Code to reproduce:
```python
import os
os.environ["MODIN_ENGINE"] = "ray" 
import numpy as np
import modin.pandas as pd
data = pd.DataFrame({'A':[np.nan,'c','b','a'],'B':['d','b','a','d'],'C':[1,2,3,4],'D':[3,4,1,3],'E':[1,1,1,1]})
data.loc[:,['D','C']] =  data.loc[:,['D','C']].astype('float')
```

Result:
```
Traceback (most recent call last):
  File "/home/yz/IdeaProjects/modin_test/test.py", line 10, in <module>
    data.loc[:,['D','C']] =  data.loc[:,['D','C']].astype('float')
  File "/home/yz/anaconda3/lib/python3.7/site-packages/modin/pandas/indexing.py", line 275, in __setitem__
    super(_LocIndexer, self).__setitem__(row_lookup, col_lookup, item)
  File "/home/yz/anaconda3/lib/python3.7/site-packages/modin/pandas/indexing.py", line 166, in __setitem__
    item = self._broadcast_item(row_lookup, col_lookup, item, to_shape)
  File "/home/yz/anaconda3/lib/python3.7/site-packages/modin/pandas/indexing.py", line 186, in _broadcast_item
    "Must have equal len keys and value when setting "
ValueError: Must have equal len keys and value when setting with an iterable
```

**Comment by devin-petersohn** [comment]
Hi @YZ576023775, try this:

```python
import os
os.environ["MODIN_ENGINE"] = "ray"
import numpy as np
import modin.pandas as pd
data = pd.DataFrame({'A':[np.nan,'c','b','a'],'B':['d','b','a','d'],'C':[1,2,3,4],'D':[3,4,1,3],'E':[1,1,1,1]})
# data.loc[:,['D','C']] = data.loc[:,['D','C']].astype('float')
data["C"] = data["C"].astype("float")
data["D"] = data["D"].astype("float")
```

Something is happening with the `loc` accessor because it is not in the same order as the data, I will investigate.

**Comment by YZ576023775** [comment]
> Hi @YZ576023775, try this:
> 
> ```python
> import os
> os.environ["MODIN_ENGINE"] = "ray"
> import numpy as np
> import modin.pandas as pd
> data = pd.DataFrame({'A':[np.nan,'c','b','a'],'B':['d','b','a','d'],'C':[1,2,3,4],'D':[3,4,1,3],'E':[1,1,1,1]})
> # data.loc[:,['D','C']] = data.loc[:,['D','C']].astype('float')
> data["C"] = data["C"].astype("float")
> data["D"] = data["D"].astype("float")
> ```
> 
> Something is happening with the `loc` accessor because it is not in the same order as the data, I will investigate.

thanks, but the scenario is that the project is written, and I hope to use modin directly without changing the code

**Comment by devin-petersohn** [comment]
I understand @YZ576023775, we will fix the bug. It is just a temporary workaround until the issue gets resolved.

**Comment by YZ576023775** [comment]
> I understand @YZ576023775, we will fix the bug. It is just a temporary workaround until the issue gets resolved.

ok, thanks

**Comment by dchigarev** [comment]
This bug is still reproducible on the current master, the problem is in how `loc/iloc` assignments work:
- Going by `loc` arguments we're computing two variables to determine the view of the frame: `row_lookup` and `col_lookup` it's **numeric indices** for index and column of the frame
- When 2D assignments occurs assignment will be done by [`_broadcast_item`](https://github.com/modin-project/modin/blob/fc3485273ff89b10c8559b08626ce2eb2198b345/modin/pandas/indexing.py#L363) method, that has these two checks at the beginning of it:
https://github.com/modin-project/modin/blob/fc3485273ff89b10c8559b08626ce2eb2198b345/modin/pandas/indexing.py#L388-L398
It checks that every value from row and column lookups exists in frame index and columns labels, however, these checks will be always false since row and column lookups are **numeric indices**
