### ISSUE TITLE
Establish proper symbol visibility when using our DB engine in python

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#1651]
When dbe is used in python scripts it seems there is a visibility problem for symbols from libDBEngine.so. 
Using smth like ctypes._dlopen('libDBEngine.so', ctypes.RTLD_GLOBAL) in scripts help so we need to create some product-level solution

**Comment by anton-malakhov** [comment]
One way to control load point and runtime load flags is to restructure the python package with __init__.py where import of dbe...so can go under changed dlopen flag defaults:
```
import sys;
oflags = sys.getdlopenflags()
sys.setdlopenflags( 1|256 )    #RTLD_LAZY+RTLD_GLOBAL
import dbe
sys.setdlopenflags( oflags )
```

**Comment by anton-malakhov** [comment]
Applying this idea into dbe.pyx (in cython), didn't help @igalink

**Comment by Garra1980** [comment]
Using setdlopenflags in modin during dbe import helps to solve segfault. Let's use this solution for now

**Comment by anton-malakhov** [comment]
though it is easy to fix on dbe side

**Comment by anton-malakhov** [comment]
parked in this branch https://github.com/intel-go/omniscidb/pull/new/syms-visibility4jit

**Comment by anton-malakhov** [comment]
This is currently fixed in https://github.com/intel-ai/modin/blob/omnisci-on-ray/modin/experimental/engines/omnisci_on_ray/frame/omnisci_worker.py#L20-L24

However, it is better to localize the issue in DBE package itself. It means re-structure it into python package with __init__.py where cythonized module is loaded by __init__.py of DBE package

**Comment by anmyachev** [comment]
I think it's no longer relevant. @Garra1980 feel free to reopen if needed.
