### ISSUE TITLE
only using modin for parallel loading of data

### ISSUE THREAD

**Issue by orenmazor** [modin-project/modin#1790]
Hey there!

I have a pandas based ETL. There's a significant section of it that's fresh financial data that I want to wrap in further testing before I switch away from baseline pandas.

But, I'd like to use modin for the parallel sql reading.

So my theory is as such:

```
import modin.pandas as modin_pandas
import pandas as baseline_pandas

df = modin_pandas.read_sql()
temp = NamedTempfile()
df.to_parquet(temp.name)
df = baseline_pandas.read_parquet(temp.name)
return df
```

I know I'm putting disk io into the game where was none before, but if I'm looking at a few hours just on the read_sql part and a minute on the read/write parquet side, this might be a win for me.

thoughts? anybody else doing this?

**Comment by devin-petersohn** [comment]
@orenmazor If you want to convert a `modin.pandas.DataFrame` to a `pandas.DataFrame`, you can use `modin_df._to_pandas()`, for now. This is not a public API and so it can change at any time, but it would prevent you from going sql->modin->parquet->pandas.

Use the `_to_pandas` with caution, but it will solve your issue here without parquet. Again, this was not meant for users to call, it is an internal convenience for going to pandas. Of course, you know your requirements better than I do, but as you can probably guess `_to_pandas` is not an API on a `pandas.DataFrame`, so going to/from pandas is not possible with this code. You must keep track of what is a Modin DataFrame vs a Pandas DataFrame.

With that said, let me know how it goes! It'll certainly be faster than going through disk.

**Comment by orenmazor** [comment]
I actually saw that one spelunking through the code. it was raising an issue for me, which is why I went with the "analog hole" type approach via parquet. let me get you a sample code. maybe its a bug

**Comment by orenmazor** [comment]
just to be sure I understand:

modin will rewrite my query to do a count of expected records (in my case ~40m), and then split them across my cores (~96), then stitch it back together right?

I saw some discussion about narrow dataframes, and most of mine are between 3 and 15 columns, so they would qualify as relatively narrow in this case. will read_sql still parallelize these?

**Comment by devin-petersohn** [comment]
Yes, you are correct. The narrow dataframe discussion is a performance optimization issue, Modin can handle narrow dataframes just fine.
