### ISSUE TITLE
Dealing with very large datasets with Modin with Ray

### ISSUE THREAD

**Issue by alokgogate** [modin-project/modin#1814]
I am trying to use modin with a ray cluster. My dataset is of 400GB with 117 columns (most of them are numeric but some are of string datatype) having ~500Million rows. I get the following problems:

1. Loading the data into a modin dataframe takes over 2hrs when on a ray cluster. When I run modin on only local node with `export MODIN_OUT_OF_CORE=true` I can do basic operations like row count, filter based on some conditions etc., but when I try to fit a model on top of this data it runs out of space (both memory and scratch disk). Is this expected or something I am missing? Ideally i would like to use modin work with the ray cluster. 
2. When trying to read a file with modin in ray cluster mode the load average of the node goes through the roof which sets off alarm bells. This looks to me as a weird behaviour, is it?

Versions:

`ray==0.8.6`
`modin==0.7.4`

Appreciate any guidance in solving this

**Comment by devin-petersohn** [comment]
Hi @alokgogate, thanks for posting. There are some things needed to make sure that there is balance across the nodes (as best as Ray can schedule).

A couple of questions:

1.) How many nodes, and how many CPUs on each node?
2.) Is the file coming from S3 or some other shared file system?
2a.) What is the file format?
3.) How are you feeding a Modin DataFrame into the model?

The first thing to try is to change the default number of partitions:

```python
import ray
ray.init(...)
import modin.pandas as pd
pd.DEFAULT_NPARTITIONS = 64  # This is best set to total number of CPU cores in the cluster

df = pd.read_<format>(...)
```

Often when data is taking a long time for ingest, the problem is that there are not enough partitions. Let me know how this goes, and please feel free to ask any other questions!

**Comment by alokgogate** [comment]
Hi @devin-petersohn, please find the answers below:
`1.) How many nodes, and how many CPUs on each node?`
A - I have 5 nodes each with 56 cores and 512GB RAM 
`2.) Is the file coming from S3 or some other shared file system?`
A - The file is stored in a shared GPFS file system
`2a.) What is the file format?`
A - The files are of of CSV (there are 100 such files each of size ~4GB) 
`3.) How are you feeding a Modin DataFrame into the model?`
A - I've tried the following method based on the example given here [modin sklean example](https://github.com/modin-project/modin/blob/master/examples/modin-scikit-learn-example.ipynb) 
```
# after importing the data into modin dataframe
from sklearn.clustering import KMeans
model = Kmeans(n_clusters=4,random_state=42).fit(df)
```

I have tried to increase the `DEFAULT_NPARTITIONS` to the total number of cores in the cluster i.e. `pd.DEFAULT_NPARTITIONS=280` and still the reading of CSV files takes time and leads to very high load average.

**Comment by devin-petersohn** [comment]
Thanks @alokgogate, this helps a lot.

I will suggest some minor changes now that I see you are loading many files.

* Try `pd.DEFAULT_NPARTITIONS = 28`.
* Change the for loop to a single concat with list comprehension.

```python
import ray 
import os
os.environ["MODIN_ENGINE"] = "ray"

ray.init(address="x.x.x.x:6380",redis_password="xxxxxxxxx")

import modin.pandas as pd
pd.DEFAULT_NPARTITIONS = 28  # to avoid many tiny partitions 


import glob
all_files = glob.glob("/path_to_filesystem/data/*.csv")

# Only do the concat once
df = pd.concat([pd.read_csv(i, sep="%") for i in all_files], ignore_index=True)
```

How long does it take to read one of the CSV files in the setup? I expect it to be somewhat higher than a single node since the file is relatively small and there are network costs, but not a significant amount higher.

Are you able to post what you are seeing with the average load as well? Reading a CSV file is very compute intensive, but I want to make sure that what you're seeing is what I would expect.

**Comment by alokgogate** [comment]
Hi @devin-petersohn, i've made the changes you suggested and following are the stats:

a. Single Node

- Time taken to read 1 file - 4seconds 

- Time taken to read all files - 9min and 30seconds

b. Cluster Mode

- Time taken to read 1 file - 47seconds

- Time taken to read all files - Failed with the following error 
> Failed to put object <object_id> into object store because its full.

I've tried to increase the object store memory but those new parameters are not being accepted when i start a worker node of ray.

The load average (for 15min) goes north of 400 when i try it with multiple concatenations. But with the method you have suggested it stays below 50

**Comment by devin-petersohn** [comment]
I spent some time this morning, with some effort I was able to reproduce some of the behavior you're seeing. We use Ray's default scheduling policy to handle the work distribution, but it looks like we're going to need to write a custom scheduler to avoid having the imbalance we are seeing. It looks like Ray is only scheduling work on one worker.

We have a scheduled release tomorrow, but another person familiar with custom scheduling policies on Ray (cc @elibol) may be able to help in the meantime, if nothing else to make sure it is not a configuration issue.

**Comment by elibol** [comment]
I ran the following code on a single node and on a cluster of 5 r5n.16xlarge instances.

```python
import ray
import os
os.environ["MODIN_ENGINE"] = "ray"

ray.init(address='...')

import modin.pandas as pd
pd.DEFAULT_NPARTITIONS = 28

%time pd.read_csv("/.../HIGGS.csv")
```


The HIGGS dataset is about 7.5GB uncompressed. I'm seeing load times around 9 seconds when running the read on a single node and on multiple nodes. On multiple nodes, I'm seeing parallel reads across different nodes (not just the head). I'm not running GPFS, but since it's a virtual filesystem, it should be all the same to Modin. @devin-petersohn please correct if I'm mistaken.

@alokgogate I'm unable to reproduce the issue you're experiencing, but I think your issue may be due to the object store using a storage device instead of RAM. Currently, by increasing object store memory, you may inadvertently be triggering Ray to use a node's HD/SSD for object store memory (maybe GPFS depending on which device `/tmp` belongs to). This may account for the experienced slowdown, as well as other strange behavior. If you're running Linux, have you made sure the space you're requesting for the object store does not exceed available shared memory space? How much space do you see allocated for `/dev/shm` when you run `df -h`? Are you requesting object store memory that exceeds the space available to `/dev/shm`?

Are you able to provide the parameters you use to start the ray head and worker nodes?

**Comment by alokgogate** [comment]
Hi @elibol 
Yes I am using Linux boxes and the output of `df -h` shows that space allocated for `/dev/shm` is 256GB. The size of object store that i have set is 128GB so it's not exceeding size of `/dev/shm`. Below are the parameters that i am giving for head node as well as worker nodes

Head Node
`ray start --head --node-ip-address='x.x.x.x' --redis-port=6380 --temp-dir=/path_to_GPFS/temp_work/ --webui-host=x.x.x.x --object-store-memory 128000000000`

Worker Nodes
`ray start --address='x.x.x.x:6380' --redis-password='XXXXXXXX' --temp-dir=/path_to_GPFS/temp_work/ --object-store-memory 128000000000`

**Comment by elibol** [comment]
Hi @alokgogate,

Those settings look okay to me. I'm wondering whether your issue may be due to something other than Modin / Ray. I'm not sure what that could be, but here are some things I would try:

1. I'm wondering whether there may be an issue with one of the worker nodes. You could try loading a single file on a few other nodes to see if the issue may be with a particular node. Or if there's some other way to test disk I/O on each node, then carry out that test.
2. It might help narrow the issue if you monitor node resource utilization while your program executes using the Ray dashboard. I would expect to see some low resource utilization (e.g. disk I/O) on some nodes, or something else that's unusual, compared to resource utilization when running on just a single node.
3. If each node has a local storage device (e.g. an SSD), I would try copying one of the csv files to each node's local storage, and try loading that file while running Ray with multiple nodes.

Let us know how it goes.

**Comment by alokgogate** [comment]
Hi @elibol,

Apologies for a delayed response 

Here's what I did based your feedback:

1. Got a few new nodes assigned and installed ray 0.8.6 installed 
2. Did a bit of stress test on the disks (large file copy) to ensure nothing is wrong with the disk 
3. Re-ran the experiment 

Even after doing the tests on new nodes I could see the same results. 

I will upgrade ray version to 0.8.7 and update if I see the same issue.

**Comment by devin-petersohn** [comment]
@alokgogate Thanks for following up, we would really like to fix what you're seeing. 

If you get the chance to upgrade to ray 0.8.7, make sure you install Modin from GitHub source: https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch

**Comment by alokgogate** [comment]
Hi @devin-petersohn , 

I managed to test out ray 0.8.7 and modin from the GitHub source master-branch. Here are my observations:
a. Single Node
- Time taken to read 1 file: 5 seconds
- TIme taken to read all files: 15min and 47 sec

b. Cluster Mode
- Time taken to read 1 file: 2min
- Time taken to read all files: After running for quite sometime (more than 4hrs ) Failed with the error Object store is full

Again I could see only a a few nodes working whilst others were mostly idle

**Comment by elibol** [comment]
Hi @alokgogate,

One thing to note here is the difference in memory layout. A single node uses shared memory, whereas cluster mode relies on distributed memory. Ray uses your cluster's network to transmit objects between nodes. Are you able to provide us with your cluster's network bandwidth (e.g. how long does it take to transmit 1 gigabyte between any 2 nodes)?

@devin-petersohn, does a read with Modin sometimes require object transmissions between nodes?

**Comment by alokgogate** [comment]
Hi @elibol ,
The network bandwidth available is 25Gbps between the nodes.
I checked with a slightly larger file of 19G and the time taken to transmit this file between 2 nodes is 50 seconds.

**Comment by devin-petersohn** [comment]
>@devin-petersohn, does a read with Modin sometimes require object transmissions between nodes?

No, it should never require this. Each node reads its partition data into the local object store.

@alokgogate When you run `ray.cluster_resources()` what do you see?

It seems like a scheduling issue, I wonder if @simon-mo (who is familiar with Modin and Ray internals) has any idea?

**Comment by alokgogate** [comment]
Hi @devin-petersohn 
here's the output of `ray.cluster_resources()`
>{'object_store_memory':6023.0,'node:X.X.X.X':1.0,'CPU':168.0,'memory':20181.0,'node:Y.Y.Y.Y':1.0,'node:Z.Z.Z.Z':1.0}

**Comment by devin-petersohn** [comment]
#2116 has an improvement to `read_csv` when you use `pd.read_csv("path", quoting=csv.QUOTE_NONE)` so it can bypass the error checking. Are you able to try installing this?

```
pip install git+https://github.com/devin-petersohn/modin.git@bugs/2115
```

It should be sufficient to only update the head node.

Then try

```python
import ray 
import os
import csv
os.environ["MODIN_ENGINE"] = "ray"

ray.init(address="x.x.x.x:6380",redis_password="xxxxxxxxx")

import modin.pandas as pd
pd.DEFAULT_NPARTITIONS = 28  # to avoid many tiny partitions 


import glob
all_files = glob.glob("/path_to_filesystem/data/*.csv")

# Only do the concat once
df = pd.concat([pd.read_csv(i, sep="%", quoting=csv.QUOTE_NONE) for i in all_files], ignore_index=True)
```

As long as you don't have any quotes with newlines this will not affect correctness.

**Comment by alokgogate** [comment]
Hi @devin-petersohn, 

I've tried the method you've suggested and I get the following error:
>AttributeError: 'Series' object has no attribute '_data' 

Even after removing `quoting=csv.QUOTE_NONE` same error

**Comment by devin-petersohn** [comment]
This probably comes from some downstream application or some code later. `_data` is an internal pandas API that we do not match. Do you have the code that triggered the `AttributeError`?

**Comment by alokgogate** [comment]
I haven't added any more lines just the ones you have given in the example. This came up during the reading part

**Comment by devin-petersohn** [comment]
Can you post the whole stack trace for this `AttributeError`? To my knowledge there's no access of pandas internals within Modin so we should get to the bottom of this.

**Comment by alokgogate** [comment]
Here's the full stack trace:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-298919eebfa7> in <module>()
----> 1 df = pd.read_csv('/path_to_filesystem/data/20200929_part1.csv"',sep="^")

/opt/modin-master/modin/pandas/io.py in parser_func(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    110         if kwargs.get("sep", sep) is False:
    111             kwargs["sep"] = "\t"
--> 112         return _read(**kwargs)
    113
    114     return parser_func

/opt/modin-master/modin/pandas/io.py in _read(**kwargs)
    125     from modin.data_management.dispatcher import EngineDispatcher
    126
--> 127     pd_obj = EngineDispatcher.read_csv(**kwargs)
    128     # This happens when `read_csv` returns a TextFileReader object for iterating through
    129     if isinstance(pd_obj, pandas.io.parsers.TextFileReader):

/opt/modin-master/modin/data_management/dispatcher.py in read_csv(cls, **kwargs)
    113     @classmethod
    114     def read_csv(cls, **kwargs):
--> 115         return cls.__engine._read_csv(**kwargs)
    116
    117     @classmethod

/opt/modin-master/modin/data_management/factories.py in _read_csv(cls, **kwargs)
     85     @classmethod
     86     def _read_csv(cls, **kwargs):
---> 87         return cls.io_cls.read_csv(**kwargs)
     88
     89     @classmethod

/opt/modin-master/modin/engines/base/io/file_reader.py in read(cls, *args, **kwargs)
     27     @classmethod
     28     def read(cls, *args, **kwargs):
---> 29         query_compiler = cls._read(*args, **kwargs)
     30         # TODO (devin-petersohn): Make this section more general for non-pandas kernel
     31         # implementations.

/opt/modin-master/modin/engines/base/io/text/csv_reader.py in _read(cls, filepath_or_buffer, **kwargs)
    186         # the limited data seen by each worker. We use pandas to compute the exact dtype
    187         # over the whole column for each column. The index is set below.
--> 188         dtypes = cls.get_dtypes(dtypes_ids)
    189
    190         partition_ids = cls.build_partition(partition_ids, row_lengths, column_widths)

/opt/modin-master/modin/backends/pandas/parsers.py in get_dtypes(cls, dtypes_ids)
     62     def get_dtypes(cls, dtypes_ids):
     63         return (
---> 64             pandas.concat(cls.materialize(dtypes_ids), axis=1)
     65             .apply(lambda row: find_common_type_cat(row.values), axis=1)
     66             .squeeze(axis=0)

~/anaconda3/lib/python3.6/site-packages/pandas/core/reshape/concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    279         verify_integrity=verify_integrity,
    280         copy=copy,
--> 281         sort=sort,
    282     )
    283

~/anaconda3/lib/python3.6/site-packages/pandas/core/reshape/concat.py in __init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    358
    359             # consolidate
--> 360             obj._consolidate(inplace=True)
    361             ndims.add(obj.ndim)
    362

~/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in _consolidate(self, inplace)
   5363         inplace = validate_bool_kwarg(inplace, "inplace")
   5364         if inplace:
-> 5365             self._consolidate_inplace()
   5366         else:
   5367             f = lambda: self._data.consolidate()

~/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in _consolidate_inplace(self)
   5345             self._data = self._data.consolidate()
   5346
-> 5347         self._protect_consolidate(f)
```

**Comment by mvashishtha** [comment]
@alokgogate if you're still having this issue, please provide a complete reproducer as well as a complete stack trace. Until then, I'm going to mark this issue as closed because it's over a year old.
