### ISSUE TITLE
Performance Issue with 'hasattr' Method

### ISSUE THREAD

**Issue by owerbat** [modin-project/modin#1927]
- Linux
- Python 3.7
- Modin 0.8.0

Currently, `hasattr(df, 'sparse')` takes much longer if `df` is instance of `modin.pandas.DataFrame` than it is `pandas.DataFrame`.

**Comment by devin-petersohn** [comment]
Thanks @owerbat, this is probably something we can speed up a bit.

**Comment by gshimansky** [comment]
This happens because `hasattr` internally calls `__getattribute__` and `__getattr__` which in turn call the function itself. And this function `DataFrame.sparse` is currently implemented as a fallback to Pandas which is really inefficient. There is an issue to implement `sparse` accessor properly https://github.com/modin-project/modin/issues/1584, it should allow access to sub-properties.

**Comment by YarShev** [comment]
I think we can fix the issue for the upcoming release adding corresponding class containing sparse methods which will be defaulting to pandas.
