### ISSUE TITLE
Performance of an Algorithm with Modin Import

### ISSUE THREAD

**Issue by owerbat** [modin-project/modin#1967]
### System information
- Linux
- Python 3.7
- Modin 0.8.0

### Describe the problem
There is a simple example of matrix multiplication using `numpy`. And the problem is when I'm using `import modin` it slows down (with `import modin`: 6.42 s; without `import modin`: 2.43 s). Is it normal that the execution time increases even when I'm not using Modin and only import it? Or may be it is unexpected behavior?

### Reproducer
```
import numpy as np
from time import perf_counter
import modin

n = 1000
n_iter = 100
t0 = perf_counter()
for _ in range(n_iter):
    a = np.random.rand(n, n)
    b = np.random.rand(n, n)
    c = np.dot(a, b)
t1 = perf_counter()
print(f'time: {t1-t0} s')
```

**Comment by anmyachev** [comment]
@owerbat thanks for posting!

I have checked that `import modin` does not affect the performance of `numpy`.
Most likely you have a case of significant fluctuations in the processor load.

Preparing the system for performance tests is not an easy task, since it is influenced by many factors, ranging from third-party applications open in parallel with benchmark, ending with an unfixed processor frequency.

Make sure that on your part, the conditions under which this script runs are as similar as possible for these 2 cases.

I also want to advise you to slightly change the test technique.

For example like this:
```python
# results for my machine: `2.11 s` vs `2.10 s with import modin`

import numpy as np
from time import perf_counter
import modin

n = 1000
n_iter = 100
test_time = [None] * n_iter

for i in range(n_iter):
    t0 = perf_counter()
    a = np.random.rand(n, n)
    b = np.random.rand(n, n)
    c = np.dot(a, b)
    test_time[i] = perf_counter() - t0

print(f'np.dot time: {min(test_time)} s')
```

One of the simplest benchmarking techniques is used here - using the minimum time value. Thus, we assume that in this case the influence of third-party factors is also minimal.

Feel free to reopen issue if needed!

**Comment by vnlitvinov** [comment]
Hi @owerbat, please kindly run the version from @anmyachev on latest `master` (if possible) and post an update.

Also make sure that you start measuring _after_ importing `modin` (as stated in your reproducer) and not accidentally before importing it. The reason I'm wondering if that was a mistake in measurement is because in 0.8.0 we AFAIR initialize some distribution engine in `modin`, not in `modin.pandas` (this initialization is now happening in `modin.pandas`), and its start time is right about 3-5 seconds on an average box, which fits your figures.

We also do a little bit of fiddling with numpy, but only in experimental mode (when you do smth like `import modin.experimental.pandas as pd`), and it should not have such an impact anyway.
