### ISSUE TITLE
Dask map_partitions equivalent on Modin?

### ISSUE THREAD

**Issue by goodwanghan** [modin-project/modin#1978]
Is there a `map_partitions` equivalent method on Modin? This is a very commonly used method, in both Spark and Dask. A main advantage is that it eliminates overhead for per item processing (`map` or `apply`).

**Comment by devin-petersohn** [comment]
Hi @goodwanghan thanks for the question!

In the API layer, no. The `map_partitions` call is actually a subset of the functionality offered in `apply`, and we don't expose it because we support `apply`. Modin will determine what kind of function is being applied, and then choose to do a `map_partitions` if it is the optimal pattern for applying the function. 

We do this for a number of reasons:

1.) `map_partitions` is a very limited API, and not as generally useful as `apply`
2.) Modin partitions differently than Spark or Dask, so you must be aware of how the data is partitioned to call the function
3.) Modin can optimize the partitioning for a given query, so the user doesn't need to even think about partitions

At lower levels in Modin, you can specify custom functions that specify `MapFunction` or `MapReduceFunction` or many others. That may be what you are looking for if you want some lower level control. We don't have any documentation on this functionality as it is relatively new, but if you'd like to dig into it, you can find the list of communication pattern functions here: https://github.com/modin-project/modin/tree/master/modin/data_management/functions

**Comment by devin-petersohn** [comment]
Closing this, feel free to reopen if there are still questions.

**Comment by aaronjbecker** [comment]
I just wanted to comment since this thread still appears in search results: [Modin does now implement functions that provide equivalent functionality](https://modin.readthedocs.io/en/stable/flow/modin/distributed/dataframe/pandas.html)  by exposing the partitions as (in the case of Ray) `ObjectRef` pointers to pandas DFs, which you can use in any function you decorate with `@ray.remote`.

**Comment by Liquidmasl** [comment]
> I just wanted to comment since this thread still appears in search results: [Modin does now implement functions that provide equivalent functionality](https://modin.readthedocs.io/en/stable/flow/modin/distributed/dataframe/pandas.html) by exposing the partitions as (in the case of Ray) `ObjectRef` pointers to pandas DFs, which you can use in any function you decorate with `@ray.remote`.

Sorry to necto this thread, but can you maybe elaborate a bit?
I am a bit lost in the documentation.

Currently I use `ray.data.from_modin(points_modin_df).map_batches(self.compute_batch_kd_trees)`
to map a function, and it works fine, but i am unsure if its the right way to do things.

**Comment by Liquidmasl** [comment]
>  We don't have any documentation on this functionality as it is relatively new, but if you'd like to dig into it, you can find the list of communication pattern functions here: https://github.com/modin-project/modin/tree/master/modin/data_management/functions

Is there documentation yet?
The link you provided does not lead anywhere sadly. 
I try to efficiantly apply a function to my df, the calculation is quite easily done vectorised so I dont want it to be done per row. With apply it might do that, but i dont know. Would be nice to be able to dig into that
