### ISSUE TITLE
Django : UserWarning: Parameters provided defaulting to pandas implementation.

### ISSUE THREAD

**Issue by AhmedSalam22** [modin-project/modin#2005]
I have discovered modin today I wanted to use it with Django i have installed modin with dask since I use windows here's how my code looks like
it is just simple read_csv
![Screenshot (312)](https://user-images.githubusercontent.com/35177448/92141585-ec546f80-ee12-11ea-98da-45facdb1c244.png)

how the data is simple 
![Screenshot (313)](https://user-images.githubusercontent.com/35177448/92141646-fe361280-ee12-11ea-82f1-a5d21fb4c39b.png)

I want to use modin with pandas to increase fast and flexibly since Django ORM is not flexible and I love pandas to handle the takes of data Analysis. 
What should I do to use modin ?

**Comment by devin-petersohn** [comment]
Thanks @AhmedSalam22 for the question!

Is `obj.uploaded_file` a `BytesIO`/`StringIO` object or some other type of object? If you can change that to the path of the file, it wouldn't fall back to the pandas implementation for your case.

We don't have parallel `BytesIO` or `StringIO` readers yet, #806 has some discussion on this.

I'm going to reflag this as a question since I don't think it's necessarily a bug.
