### ISSUE TITLE
Local variables not yet supported in eval.

### ISSUE THREAD

**Issue by AhmedSalam22** [modin-project/modin#2006]
I encounter this message when trying to use modin 
Local variables not yet supported in eval.
To request implementation, send an email to feature_requests@modin.org

here's a code 
![Screenshot (314)](https://user-images.githubusercontent.com/35177448/92144852-9b934580-ee17-11ea-8b1a-cb57298ab752.png)

**Comment by devin-petersohn** [comment]
Thanks @AhmedSalam22 for the request! 

This is related to (but not the same as) #1369. Since the data is distributed, not all workers will have access to the variable so it must be copied/broadcasted. This may not be desired in many cases for performance reasons, so we're still working on some way to solve this issue generally.

**Comment by aregm** [comment]
@anmyachev Anatoly, can you please update and close this issue?
