### ISSUE TITLE
Use Ray to parallelize `read_hdf`

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#204]
### Describe the problem

Currently, `read_hdf` just defaults to the pandas implementation. It will be faster if we use Ray (similar to how `read_csv` and `read_parquet` are implemented.

Right now our `io.py` file is a bit disorganized, and could use a minor refactor (#203).

This is a good issue for a new contributor that is familiar with hdf. Please respond to this issue with any questions or comments about this implementation.

### Source code / logs

[Link to source](https://github.com/modin-project/modin/blob/master/modin/pandas/io.py#L477)

**Comment by eavidan** [comment]
hi @devin-petersohn 
I have implemented this, which was basically a duplication of the read_parquet
A lot of duplicated code since I did not want to refactor too much, and I know there is #203 
before I submit the PR, can you please take a look and see [this](https://github.com/eavidan/modin/commit/efd19b8bf56a2074e5a3983a6f0dffbb9a78caac) is indeed what we want
thanks

**Comment by devin-petersohn** [comment]
Thanks @eavidan! That is exactly what I think we need. #203 seems like it has not yet been completed, and since this has, let's go ahead and merge this first.

**Comment by devin-petersohn** [comment]
Closed via #264
