### ISSUE TITLE
Fresh install requires pyarrow and pyarrow.gandiva

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#2090]
This code is run to cause this requirement:

https://github.com/modin-project/modin/blob/90adc7d7cbbb424c27f0618b94cb006af06dc5e7/modin/backends/pyarrow/query_compiler.py#L20-L21

This is not in the `setup.py` requirements, but I don't think we should add it. We should probably just wrap that in a conditional.

**Comment by vnlitvinov** [comment]
Could you please provide a simple reproducer?
This is not expected to happen after https://github.com/modin-project/modin/pull/1601

**Comment by devin-petersohn** [comment]
In your Python or conda environment
```
pip uninstall pyarrow
```

Then on master

```python
import modin.pandas as pd
```

**Comment by dchigarev** [comment]
If we'll uninstall pyarrow and try to import Modin we will see the following traceback:
```
>>> import modin.pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/localdisk/dchigare/repos/modin_bp/modin/pandas/__init__.py", line 181, in <module>
    from .concat import concat
  File "/localdisk/dchigare/repos/modin_bp/modin/pandas/concat.py", line 21, in <module>
    from modin.backends.base.query_compiler import BaseQueryCompiler
  File "/localdisk/dchigare/repos/modin_bp/modin/backends/__init__.py", line 16, in <module>
    from .pyarrow import PyarrowQueryCompiler
  File "/localdisk/dchigare/repos/modin_bp/modin/backends/pyarrow/__init__.py", line 14, in <module>
    from .query_compiler import PyarrowQueryCompiler
  File "/localdisk/dchigare/repos/modin_bp/modin/backends/pyarrow/query_compiler.py", line 20, in <module>
    import pyarrow as pa
ModuleNotFoundError: No module named 'pyarrow'
```
which tells us that root cause of the problem is this init file:
https://github.com/modin-project/modin/blob/eaa77aa72fd9fc56435a286d269ebc3baca07282/modin/backends/__init__.py#L13-L18

importing `BaseQueryCompiler` at the modin initialization stage triggers to import every query compilers that we have, which I think is incorrect, because different backends have different dependencies, and we don't want to force the users to have all of them, if he wants to use some one backend

**Comment by dchigarev** [comment]
these changes in `__init__.py` file was done to more handy importing different backends, like just:
```python
from modin.backends import PandasQueryCompiler
```
however, in reality that works wrong, I think we should revert these changes for now

**Comment by vnlitvinov** [comment]
@dchigarev nice analysis, it took me 5 minutes to make a fix after that, thx!
