### ISSUE TITLE
Performance analysis for Plasticc benchmark

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#2184]
We need to be not slower ibis variant

**Comment by ienkovich** [comment]
The current ETL time (measured on a Xeon 8276L) is 71.32174s. There are several reasons for slower performance comparing to Ibis version:
1. Ibis version has unordered `groupby` while Pandas and Modin use ordered `groupby` because in Pandas sorting is enabled by default.
2. Modin version has Calcite disabled by default
3. Ibis version uses manually chosen fragment size (32M) and Modin splits tables evenly between all CPU cores (~1.7M). This causes huge overhead on groupby execution due to initialization of many result sets and reduction (saw 40sec reduction time in debug timers). 
If we remove these differences then results look similar:
```
Modin_on_omnisci results:
    t_readcsv = 3.30331 s
    t_etl = 17.48384 s
    t_connect = 0.00000 s
```
```
Ibis results:
    t_readcsv = 5.14989 s
    t_etl = 15.11188 s
    t_connect = 0.41656 s
```
For Modin read CSV time includes parsing only and data import goes to ETL part.

**Comment by Garra1980** [comment]
Currently we have modin-on-omnisci time is even better than ibis version thus closing
