### ISSUE TITLE
NYC Taxi and Census benchmark performance analysis on Modin on Ray.

### ISSUE THREAD

**Issue by aregm** [modin-project/modin#2202]

**Comment by gshimansky** [comment]
NY Taxi benchmark has the following Modin function still defaulting to Pandas
```
UserWarning: reset_index defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
UserWarning: reset_index defaulting to pandas implementation.
UserWarning: sort_values defaulting to pandas implementation.
```

**Comment by gshimansky** [comment]
When Modin uses Ray engine and is run on a system with multiple CPU cores the process slows down to a crawl. NY Taxi benchmark running on 112 CPUs didn't finish in 2 days. The problem is exacerbated by this bug https://github.com/intel-ai/omniscripts/issues/191 that `MODIN_CPUS` has no effect for omniscripts benchmarks, so `num_cpus` parameter has to be add manually in `ray.init`. With number `4` benchmark usually completes.
