### ISSUE TITLE
Unexpected Performance Creating Dataframes

### ISSUE THREAD

**Issue by mmortazavi** [modin-project/modin#232]
### The problem
I do not see the expected performance creating the provided examples :

```
import numpy as np
import modin.pandas as pd

frame_data = np.random.randint(0, 100, size=(2**12, 2**8))
```

```
%%timeit
df = pd.DataFrame(frame_data)
```
**76 ms ± 3.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)**

```
import pandas as pd
```

```
%%timeit
df = pd.DataFrame(frame_data)
```
**83.8 µs ± 3.69 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)**

This test shows _modin_ is about 1000x slower than  the original _pandas_. I have tried with different sizes of _frame_data_ (very small-> very large, still normal pandas seems giving me better timing). Am I missing something here? I see most of the benchmarks reporting significant speedup reading _csv_ files (that I have not tested yet), but shouldn't we expect almost the same speedup creating the dataframe? 

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.13.5
- **Modin installed from (source or binary)**: pip install modin
- **Modin version**: 0.2.2
- **Python version**: 3.6.6
- **Numpy version**: 1.15.2
- **Jupyter Notebook**: 4.4.0

**Comment by devin-petersohn** [comment]
Creating a DataFrame from a single numpy array will always be faster in pandas. This is because in Modin, we have to distribute and parallelize the data (which requires communication between the workers). I can explain why here:

numpy arrays are not distributed objects. In Ray, workers are essentially processes (not threads). For the workers to be able to process the data, we need to partition it and send each partition to a worker. This is where the overhead comes in that you are seeing. There are perhaps some things we can do to speed it up, but since pandas is essentially wrapping numpy, it will be faster because there are no communication overheads.

When we start with something like read_csv, we can use all of the workers to read their partition individually and effectively at the same time. This allows us to have faster data ingest than pandas.

This behavior is expected because of the communication overhead. pandas can just do some simple checks and add some metadata and it is done. In Modin, we have to distribute and parallelize the data so it can be operated on in-parallel (on top of the checks). Fortunately, most real-world workflows start with data that comes from some format, so that is why we have prioritized `read_csv` and `read_parquet`.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
