### ISSUE TITLE
DataFrame.groupby by multiple columns 

### ISSUE THREAD

**Issue by valsecchi** [modin-project/modin#234]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  macOS Mojave
- **Modin installed from (source or binary)**: pip install modin
- **Modin version**: 0.2.2
- **Python version**:3.6.6
- **Exact command to reproduce**: DataFrame.groupby([column1,columns2])

### Describe the problem

Hi guys, I've noticed an incompatibility with the regular pandas.DataFrame.groupby()
I've this DataFrame with multiple columns:

```
import pandas as pd  
df = pd.DataFrame(np.concatenate([np.ones([2,3]),2*np.ones([1,3]),3*np.ones([3,3])]),columns['a','b','c'])
for i in df.groupby(['a','b']):
    display(i[0],i[1])
```
it does the right thing returning 3 GroupBy objects, while when you tr:

```
import modin.pandas as pd  
df = pd.DataFrame(np.concatenate([np.ones([2,3]),2*np.ones([1,3]),3*np.ones([3,3])]),columns['a','b','c'])
for i in df.groupby(['a','b']):
    display(i[0],i[1])
```

it seems to not grouping in the right way and it returns the name of the column.

**Comment by devin-petersohn** [comment]
Thanks for the report!

It looks like the way we are presenting the groups when iterating over the grouped dataframe is causing this issue. https://github.com/modin-project/modin/blob/master/modin/pandas/groupby.py#L77. We use a different way of grouping for the iterator because it is kind of a special case. I will get this fixed, thanks again for the report!

**Comment by NaderNazemi** [comment]
I am having issues just ding a regular groupby in modin in a for loop.

**Comment by devin-petersohn** [comment]
Thanks for commenting @NaderNazemi, would you be able to post new issue with more details so we can get it resolved?
