### ISSUE TITLE
DOCS: indicate order of option items in commit message

### ISSUE THREAD

**Issue by reshamas** [modin-project/modin#2434]
The current instructions are not clear on how `-s` should be included in commit message.  This works:  
`git commit -m "message" -s`

file:  https://github.com/modin-project/modin/blob/master/docs/CONTRIBUTING.rst

**Comment by mvashishtha** [comment]
I think the current instructions are clear enough: https://modin.readthedocs.io/en/0.15.3/development/contributing.html#certificate-of-origin-v-1-1

**Comment by reshamas** [comment]
> I think the current instructions are clear enough: https://modin.readthedocs.io/en/0.15.3/development/contributing.html#certificate-of-origin-v-1-1

If you say so.  :)

**Comment by mvashishtha** [comment]
@reshamas thank you for responding to this issue even though it's so old!

It's a little hard to figure out what the contributing instructions said at the time you reported this issue, because the file has moved around since then. I assumed that there were no instructions about signing commits then. How could we make the current documentation clearer? I assume that readers know that command line flags for commands like `git commit` can appear in any order. Is that a bad assumption?

**Comment by reshamas** [comment]
I believe this issue was inspired by a challenge at an online sprint at PyData Global 2021 with @devin-petersohn.

Maybe the best way to see if the instructions are clear is to check again at a sprint or with new contributors.  I haven't contributed to modin since last October.
