### ISSUE TITLE
"Task is a driver task and so the object created by ray.put could not be reconstructed"

### ISSUE THREAD

**Issue by zeevikal** [modin-project/modin#245]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04 (docker image
- **Modin installed from (source or binary)**: pip from master branch
- **Modin version**: 0.2.2
- **Python version**: 3.6
- **Exact command to reproduce**:
```
import modin.pandas as pd
pd.read_gbq(query, project_id, private_key, dialect)
```

### Describe the problem
I'm trying to use `read_gbq` (google bigquery) with modin 0.2.2 so I pip the latest version from master branch in modin repo (github).
I'm running my code on docker image (with Kubernetes cluster).
I'm getting this error message - `Task is a driver task and so the object created by ray.put could not be reconstructed`

I googled it and found out that the problem is with `ray` library, maybe with redis shell memory, so I forked `modin` repo and added `object_store_memory=1e9` to pandas initializer.
after running the code (with the new variable) I'm getting new error message - `Could not connect to socket /tmp/plasma_storeXXX`.

I'm not sure if the problem caused because I'm running my code on docker image and `ray` library trying to run a new image with redis in it. maybe I'm wrong.

thanks for helping. 

### Source code / logs
```
try:
    if threading.current_thread().name == "MainThread":
        ray.init(
            redirect_output=True,
            include_webui=False,
            redirect_worker_output=True,
            use_raylet=True,
            object_store_memory=1e9,
        )
except AssertionError:
    pass
```

**Comment by devin-petersohn** [comment]
When you get the `Task is a driver task and so the object created by ray.put could not be reconstructed` message, it means there is not enough memory to use the DataFrame (apologies about the generic nature of the message, we are working on this).

Re: `Could not connect to socket /tmp/plasma_storeXXX`: There is an open issue about this in the Ray repo: https://github.com/ray-project/ray/issues/3223.
cc @robertnishihara 

Side note: Instead of editing the source, you can `ray.init` before you `import modin.pandas as pd`

```python
import ray
ray.init(object_store_memory=10**9)
import modin.pandas as pd
# rest of the code here
```

This way you can customize your Ray environment and Modin will automatically connect to that Ray instance.

**Comment by robertnishihara** [comment]
@devin-petersohn note that https://github.com/ray-project/ray/pull/3243 changed the default behavior to cap object store memory at 20GB. This can still be overridden by setting `object_store_memory`.

**Comment by devin-petersohn** [comment]
After doing some investigating on where this is happening, I have been unable to find the object in Ray's object_table. I will be opening an issue on Ray to track that.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
