### ISSUE TITLE
Import redis.exceptions.DataError

### ISSUE THREAD

**Issue by Timonzimm** [modin-project/modin#259]
Hi,
While simply trying to install modin and importing it, I get the following error from Redis:
`redis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a byte, string or number first.`

Full trace:
![image](https://user-images.githubusercontent.com/5808319/48560029-33473d00-e8ed-11e8-96ec-1d7ea04460e3.png)

Is this a known issue or dependency missing?

Thank you for your help!

**Comment by devin-petersohn** [comment]
Hi @Timonzimm thanks for posting this! It looks like something is going wrong when the Ray runtime is starting up.

Can you tell me your OS distribution (including which version)?

Also, can you try the following:
```python
import ray
ray.init()
```
Does that produce the same error?

cc @robertnishihara: I haven't been able to find an open issue about this in Ray.

**Comment by jmcamza** [comment]
Hi, @devin-petersohn , I have exactly the same issue, in different OS and platforms, I tried in a cluster, in my mac, in ubuntu, with and without virtual environments, different python versions from 2.7, 3.5, 3.6 and 3.7 and still can make it work.

import ray
ray.init()

gives exactly the same error

**Comment by devin-petersohn** [comment]
The problem is with the redis dependency in Ray. I was able to reproduce the error by upgrading my redis install.

Here is the fix:

`pip install redis==2.10.6`

Then you should be able to run Modin and Ray without the redis error.

**Comment by devin-petersohn** [comment]
I created an issue in Ray to get this fixed. https://github.com/ray-project/ray/issues/3334

**Comment by devin-petersohn** [comment]
For now, we have pinned Modin to `redis==2.10.6` (see #262). We will do a point release for users.

**Comment by Timonzimm** [comment]
It indeed solved the problem, thank you for the reactivity!
Unfortunately I run into another issue now from "pandas.errors.ParserError " when I `read_csv`. This package doesn't seem to be as robust/polished as it might be needed unortunately.

**Comment by devin-petersohn** [comment]
@Timonzimm Does the error look like the one in #247? We can move the conversation there if it does, otherwise it would be good to open another issue to track it. These are usually environment issues that are not easy to debug without being able to reproduce them.

Regarding your comments on the polished nature of the project, we are actively accepting contributors. The Modin repo is 4 months old, and we started the proof of concept in February of this year. If you'd like to contribute to the future of the project, I would be happy to point you to some open issues that are good for first time contributors.

**Comment by boxigg** [comment]
hi,@devin-petersohn ,
on my Fedora Workstation 29, i did :
pip install redis==2.10.6,
then
import modin.pandas as pd
the following error happened:
/home/boxi/anaconda3/envs/boxquant/bin/python /home/boxi/quant/boxquant/config/ctp_sqlite_sqcripts.py
WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-04-24_17-35-54_15822/logs.
Waiting for redis server at 127.0.0.1:52055 to respond...
Waiting for redis server at 127.0.0.1:40906 to respond...
Starting Redis shard with 10.0 GB max memory.
WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 8335433728 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
Starting the Plasma object store with 10.0 GB memory using /tmp.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0424 17:35:54.506184 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 50 more times
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0424 17:35:54.509299 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 50 more times
E0424 17:35:54.606878 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 49 more times
E0424 17:35:54.609704 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 49 more times
E0424 17:35:54.707151 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 48 more times
E0424 17:35:54.710005 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 48 more times
E0424 17:35:54.807734 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 47 more times
E0424 17:35:54.810328 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 47 more times
E0424 17:35:54.908341 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 46 more times
E0424 17:35:54.910764 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 46 more times
E0424 17:35:55.008977 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 45 more times
E0424 17:35:55.010982 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 45 more times
E0424 17:35:55.109438 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 44 more times
E0424 17:35:55.111712 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 44 more times
E0424 17:35:55.210038 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 43 more times
E0424 17:35:55.212116 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 43 more times
E0424 17:35:55.310714 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 42 more times
E0424 17:35:55.312721 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 42 more times
E0424 17:35:55.411315 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 41 more times
E0424 17:35:55.413293 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 41 more times
E0424 17:35:55.511747 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 40 more times
E0424 17:35:55.513878 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 40 more times
E0424 17:35:55.611965 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 39 more times
E0424 17:35:55.614096 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 39 more times
E0424 17:35:55.712563 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 38 more times
E0424 17:35:55.714285 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 38 more times
E0424 17:35:55.812779 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 37 more times
E0424 17:35:55.814910 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 37 more times
E0424 17:35:55.913388 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 36 more times
E0424 17:35:55.915520 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 36 more times
E0424 17:35:56.013998 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 35 more times
E0424 17:35:56.016012 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 35 more times
E0424 17:35:56.114574 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 34 more times
E0424 17:35:56.116686 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 34 more times
E0424 17:35:56.214918 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 33 more times
E0424 17:35:56.217034 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 33 more times
E0424 17:35:56.315464 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 32 more times
E0424 17:35:56.317617 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 32 more times
E0424 17:35:56.415799 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 31 more times
E0424 17:35:56.418257 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 31 more times
E0424 17:35:56.516168 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 30 more times
E0424 17:35:56.518838 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 30 more times
E0424 17:35:56.616492 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 29 more times
E0424 17:35:56.619168 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 29 more times
E0424 17:35:56.716696 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 28 more times
E0424 17:35:56.719399 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 28 more times
E0424 17:35:56.817286 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 27 more times
E0424 17:35:56.819984 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 27 more times
E0424 17:35:56.917877 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 26 more times
E0424 17:35:56.920507 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 26 more times
E0424 17:35:57.018157 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 25 more times
E0424 17:35:57.020800 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 25 more times
E0424 17:35:57.118706 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 24 more times
E0424 17:35:57.121376 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 24 more times
E0424 17:35:57.219295 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 23 more times
E0424 17:35:57.221974 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 23 more times
E0424 17:35:57.319676 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 22 more times
E0424 17:35:57.322352 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 22 more times
E0424 17:35:57.420177 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 21 more times
E0424 17:35:57.422863 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 21 more times
E0424 17:35:57.520512 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 20 more times
E0424 17:35:57.523238 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 20 more times
E0424 17:35:57.621106 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 19 more times
E0424 17:35:57.623762 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 19 more times
E0424 17:35:57.721662 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 18 more times
E0424 17:35:57.724355 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 18 more times
E0424 17:35:57.822393 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 17 more times
E0424 17:35:57.825044 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 17 more times
E0424 17:35:57.922927 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 16 more times
E0424 17:35:57.925622 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 16 more times
E0424 17:35:58.023386 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 15 more times
E0424 17:35:58.026187 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 15 more times
E0424 17:35:58.124063 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 14 more times
E0424 17:35:58.126826 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 14 more times
E0424 17:35:58.224673 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 13 more times
E0424 17:35:58.227442 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 13 more times
E0424 17:35:58.325214 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 12 more times
E0424 17:35:58.327872 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 12 more times
E0424 17:35:58.425904 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 11 more times
E0424 17:35:58.428555 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 11 more times
E0424 17:35:58.526495 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 10 more times
E0424 17:35:58.529139 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 10 more times
E0424 17:35:58.626967 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 9 more times
E0424 17:35:58.629629 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 9 more times
E0424 17:35:58.727138 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 8 more times
E0424 17:35:58.729840 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 8 more times
E0424 17:35:58.827760 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 7 more times
E0424 17:35:58.829989 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 7 more times
E0424 17:35:58.928319 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 6 more times
E0424 17:35:58.930469 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 6 more times
E0424 17:35:59.028827 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 5 more times
E0424 17:35:59.031031 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 5 more times
E0424 17:35:59.129384 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 4 more times
E0424 17:35:59.131528 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 4 more times
E0424 17:35:59.229974 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 3 more times
E0424 17:35:59.232112 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 3 more times
E0424 17:35:59.330598 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 2 more times
E0424 17:35:59.332716 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 2 more times
E0424 17:35:59.430876 15843 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 1 more times
E0424 17:35:59.432942 15822 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store, retrying 1 more times
F0424 17:35:59.531457 15843 object_store_notification_manager.cc:23]  Check failed: _s.ok() Bad status: IOError: Could not connect to socket /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store
*** Check failure stack trace: ***
*** Aborted at 1556098559 (unix time) try "date -d @1556098559" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e800003de3) received by PID 15843 (TID 0x7f4b2792c740) from PID 15843; stack trace: ***
    @     0x7f4b27e4af70 (unknown)
    @     0x7f4b2796953f __GI_raise
    @     0x7f4b27953895 __GI_abort
    @           0x5b85fd google::logging_fail()
    @           0x5b8626 google::LogMessage::Fail()
    @           0x5b8572 google::LogMessage::SendToLog()
    @           0x5b7ef6 google::LogMessage::Flush()
    @           0x5b7d05 google::LogMessage::~LogMessage()
    @           0x5a7788 arrow::util::ArrowLog::~ArrowLog()
Traceback (most recent call last):
  File "/home/boxi/quant/boxquant/config/ctp_sqlite_sqcripts.py", line 387, in <module>
    import modin.pandas as pd
  File "/home/boxi/anaconda3/envs/boxquant/lib/python3.7/site-packages/modin/pandas/__init__.py", line 182, in <module>
    initialize_ray()
  File "/home/boxi/anaconda3/envs/boxquant/lib/python3.7/site-packages/modin/pandas/__init__.py", line 174, in initialize_ray
    object_store_memory=object_store_memory,
  File "/home/boxi/anaconda3/envs/boxquant/lib/python3.7/site-packages/ray/worker.py", line 1530, in init
    @           0x56380d ray::ObjectStoreNotificationManager::ObjectStoreNotificationManager()
    driver_id=driver_id)
  File "/home/boxi/anaconda3/envs/boxquant/lib/python3.7/site-packages/ray/worker.py", line 1882, in connect
    @           0x51ecd3 ray::ObjectManager::ObjectManager()
    @           0x4c3ac4 ray::raylet::Raylet::Raylet()
    plasma.connect(info["store_socket_name"]))
  File "pyarrow/_plasma.pyx", line 789, in pyarrow._plasma.connect
  File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Could not connect to socket /tmp/ray/session_2019-04-24_17-35-54_15822/sockets/plasma_store

Process finished with exit code 1

**Comment by devin-petersohn** [comment]
Hi @boxigg, thanks for posting! 

Your error looks unrelated to the original issue, rather looks like #468. Should we move the conversation there?

**Comment by boxigg** [comment]
Hi@devin-petersohn, you are right,  https://github.com/modin-project/modin/issues/468 is what i meet.

**Comment by arjuns2020** [comment]
I am trying to load url as keys to redis and getting this error 

this is how my URL looks like: 
https://d2i6pukzef2l69.cloudfront.net/nrm/images/STTM_VE;MEAS_CD_SEM/1A1JA/RUN01/1A1JA_STTM_VE_MEAS_CD_SEM_{S9_STTM_TEST_S9_STTM_TEST_M1}_DX6DY11SDX2SDY10_2020-10-20_04-25-17.JPG
https://d2i6pukzef2l69.cloudfront.net/nrm/images/STTM_VE;MEAS_CD_SEM/1A1JA/RUN01/1A1JA_STTM_VE_MEAS_CD_SEM_{S9_STTM_TEST_S9_STTM_TEST_M1}_DX6DY11SDX13SDY41_2020-10-20_04-25-17.JPG
https://d2i6pukzef2l69.cloudfront.net/stst/images/STTM_VE;MEAS_CD_SEM/A7HXM/RUN01/A7HXM_STTM_VE_MEAS_CD_SEM_{S9_STTM_KLA_TEST_2_S9_STTM_TEST_M1}_DX6DY9SDX7SDY23_2020-10-20_08-02-12.JPG
https://d2i6pukzef2l69.cloudfront.net/stst/images/STTM_VE;MEAS_CD_SEM/A7HXM/RUN01/A7HXM_STTM_VE_MEAS_CD_SEM_{S9_STTM_KLA_TEST_2_S9_STTM_TEST_M1}_DX6DY9SDX10SDY33_2020-10-20_08-02-12.JPG
https://d2i6pukzef2l69.cloudfront.net/nrm/images/STTM_VE;MEAS_CD_SEM/V92KI/RUN01/V92KI_STTM_VE_MEAS_CD_SEM_{S9_STTM_TEST_3_S9_STTM_TEST_M1}_DX11DY14SDX11SDY14_2020-10-20_02-24-06.JPG
https://d2i6pukzef2l69.cloudfront.net/nrm/images/STTM_VE;MEAS_CD_SEM/V92KI/RUN01/V92KI_STTM_VE_MEAS_CD_SEM_{S9_STTM_TEST_3_S9_STTM_TEST_M1}_DX11DY14SDX6SDY35_2020-10-20_02-24-06.JPG
https://d2i6pukzef2l69.cloudfront.net/nrm/images/STTM_VE;MEAS_CD_SEM/V92KI/RUN01/V92KI_STTM_VE_MEAS_CD_SEM_{S9_STTM_TEST_2_S9_STTM_TEST_M1}_DX5DY9SDX10SDY33_2020-10-20_02-24-06.JPG
https://d2i6pukzef2l69.cloudfront.net/nrm/images/STTM_VE;MEAS_CD_SEM/V92KI/RUN01/V92KI_STTM_VE_MEAS_CD_SEM_{S9_STTM_TEST_2_S9_STTM_TEST_M1}_DX5DY9SDX7SDY23_2020-10-20_02-24-06.JPG
https://d2i6pukzef2l69.cloudfront.net/nrm/images/STTM_VE;MEAS_CD_SEM/V92KI/RUN01/V92KI_STTM_VE_MEAS_CD_SEM_{S9_STTM_TEST_2_S9_STTM_TEST_M1}_DX4DY6SDX10SDY33_2020-10-20_02-24-06.JPG
https://d2i6pukzef2l69.cloudfront.net/nrm/images/STTM_VE;MEAS_CD_SEM/V92KI/RUN01/V92KI_STTM_VE_MEAS_CD_SEM_{S9_STTM_TEST_2_S9_STTM_TEST_M1}_DX4DY6SDX7SDY23_2020-10-20_02-24-06.JPG
https://d2i6pukzef2l69.cloudfront.net/nrm/images/STTM_VE;MEAS_CD_SEM/V92KI/RUN01/V92KI_STTM_VE_MEAS_CD_SEM_{S9_STTM_TEST_2_S9_STTM_TEST_M1}_DX16DY5SDX10SDY33_2020-10-20_02-24-06.JPG
https://d2i6pukzef2l69.cloudfront.net/nrm/images/STTM_VE;MEAS_CD_SEM/V92KI/RUN01/V92KI_STTM_VE_MEAS_CD_SEM_{S9_STTM_TEST_2_S9_STTM_TEST_M1}_DX16DY5SDX7SDY23_2020-10-20_02-24-06.JPG
https://d2i6pukzef2l69.cloudfront.net/nrm/images/STTM_VE;MEAS_CD_SEM/V92KI/RUN01/V92KI_STTM_VE_MEAS_CD_SEM_{S9_STTM_TEST_2_S9_STTM_TEST_M1}_DX14DY10SDX10SDY33_2020-10-20_02-24-06.JPG
https://d2i6pukzef2l69.cloudfront.net/nrm/images/STTM_VE;MEAS_CD_SEM/V92KI/RUN01/V92KI_STTM_VE_MEAS_CD_SEM_{S9_STTM_TEST_2_S9_STTM_TEST_M1}_DX14DY10SDX7SDY23_2020-10-20_02-24-06.JPG
https://d2i6pukzef2l69.cloudfront.net/nrm/images/STTM_VE;MEAS_CD_SEM/1P3FM/RUN01/1P3FM_STTM_VE_MEAS_CD_SEM_{S9_STTM_TEST_2_S9_STTM_TEST_M1}_DX4DY6SDX7SDY23_2020-10-20_02-24-06.JPG

ERROR: 
Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.
