### ISSUE TITLE
Clean up troubleshooting documentation

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#2635]
Everything on troubleshooting documentation is outdated, need to update.

**Comment by dorisjlee** [comment]
The Troubleshooting page should probably be under the user guide rather than hidden away in the Developer section. It might also be good to split out the guide into "FAQs" (i.e., common questions with links to specific pages in the docs, act a bit like an inverted index) with "Troubleshooting" (i.e., Debugging Modin with error messages and solution).
