### ISSUE TITLE
speed up _compute_dtypes function

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2751]
The function works extremely inefficiently when the number of columns is approximately equal to the number of rows.

For example, if `df.shape = (5000, 5000)` and `MODIN_CPUS=44` then `count_partitions=44^2`.

**Comment by anmyachev** [comment]
@pyrito need someone to check how long this function takes on the master in the case above.

**Comment by Retribution98** [comment]
@anmyachev 
This issue was fixed in PR #7245.
Time results for DF with shape (5600, 5600) using 112 CPU:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ksuvorov/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ksuvorov/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">


  | before PR | after PR
-- | -- | --
Time, s | 4.6 | 1.8



</body>

</html>

**Comment by anmyachev** [comment]
> @anmyachev This issue was fixed in PR #7245. Time results for DF with shape (5600, 5600) using 112 CPU:
> 
>  	before PR	after PR
> Time, s	4.6	1.8

Good!
