### ISSUE TITLE
modin fails to correctly deliver division results in dataframe rows

### ISSUE THREAD

**Issue by holazzer** [modin-project/modin#2857]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin version** (`modin.__version__`):  0.9.0
- **Python version**: 3.7.2
- **Code we can use to reproduce**: `new['effratio'] = new['efflen']/new['txtlen']`

### Describe the problem
If you directly use rows in a DataFrame to do division, the result is not correct. I discovered this when I want to calculate a ratio. Some ratio values are larger than 1. I ran the same code with original pandas and it delivered the correct result.

I have listed several items in this dataframe for you to see the problem. See the image.

`new` is a DataFrame object I read in.

![issue](https://user-images.githubusercontent.com/45134013/110804696-5f0b3f80-82bb-11eb-8adc-eab68580be71.png)

**Comment by devin-petersohn** [comment]
Hi @holazzer thanks for the report!

I think I can reproduce the issue locally, it is happening because of non-distinct index values. The source of the problem is this:

```python
import modin.pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(0, 100, size=(2**10, 2**6))).add_prefix("col")
df.index = [i // 3 for i in df.index]
df["col0"] / df["col1"]  # this does a join on the index
```

pandas doesn't seem to do the join on the index when the values are duplicated. I will investigate the source of this and get it resolved quickly. 

Thank you @holazzer for the detail, this would have been very difficult to debug without your explanation and figures!

**Comment by devin-petersohn** [comment]
Quick update, when trying to generalize pandas behavior, we are doing the join on the index, but pandas doesn't do an inner join when the index objects are equivalent. It should be a quick fix.

This results in the join in pandas:
```python
df["col0"] / df["col1"].iloc[1:]  # 3x the number of rows
```
but this does not:
```python
df["col0"] / df["col1"]
```
