### ISSUE TITLE
AttributeError: module 'modin.pandas' has no attribute 'options'

### ISSUE THREAD

**Issue by tsdev** [modin-project/modin#291]
I just installed modin and ray (0.6.0), I couldn't find the necessary version of ray (0.5.3) on pypi and it seems modin is incompatible with the current version of ray.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.13.6
- **Modin installed from (source or binary)**: binary
- **Modin version**: 0.2.5
- **Python version**: 3.7.0
- **Exact command to reproduce**: `import modin.pandas as pd`

### Describe the problem
After importing modin, it returns the following error:
```
WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2018-12-05_11-16-44_6969/logs.
Waiting for redis server at 127.0.0.1:57353 to respond...
Waiting for redis server at 127.0.0.1:41858 to respond...
Starting the Plasma object store with 6.871947672999999 GB memory using /tmp.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-23b6df018f82> in <module>()
      3 from datetime import datetime, timedelta
      4 from matplotlib import pyplot as plt
----> 5 pd.options.display.max_rows = 100
      6 cache_path = '../cache/'
      7 get_ipython().run_line_magic('load_ext', 'line_profiler')

AttributeError: module 'modin.pandas' has no attribute 'options'
```

**Comment by devin-petersohn** [comment]
Hi @tsdev, thanks for posting this! Since you are using Python 3.7, Ray 0.6 is the only version available.

Modin does not yet support `pd.options`. Most people seem to use this to update the display rows/columns, as your code is, but we have not had the chance to implement it yet. 

One temporary fix (until it is implemented) is to remove that line `pd.options.display.max_rows = 100`. Pull requests are also welcome!

I am updating the title to help future contributors. This should be a good first issue, so if anyone is interested in contributing this, feel free.

**Comment by devin-petersohn** [comment]
Closing via #538
