### ISSUE TITLE
Modin goes into a never-ending process that normally takes 1 second in Pandas 

### ISSUE THREAD

**Issue by bkrdmr** [modin-project/modin#2972]
### System information
- **OS Platform and Distribution (Linux Ubuntu 20.04 (I also tried in WSL 2 Ubuntu 20.04))**:
- **Modin version** (`modin.__version__`): 0.9.1 (tried in [dask] and [ray]
- **Python version**: 3.9.2
- **Code we can use to reproduce**:

`df_subset = df.iloc[0:250000]
gp = df_subset.groupby('target', as_index=False).aggregate(lambda tdf: tdf.unique().tolist())

edges = []

for x, y in gp.itertuples(index=False):
    if len(y) > 1:
        edges.extend(list(combinations(sorted(y),2)))

ht_pair_count = Counter(edges)
weight_threshold = 1
edges_list_weigths = np.array([(ht1, ht2, w) for (ht1, ht2), 
                               w in ht_pair_count.items() if w >=weight_threshold])`

### Describe the problem

Modin seems to enter a never-ending loop/process after the line: edges=[]. that specific for loop takes around 1 second in Pandas. So this snippet keeps running forever. 

When I test it line by line, the problem seems to be emerging in the following section: 

`edges = []
for x, y in gp.itertuples(index=False):
    if len(y) > 1:
        edges.extend(list(combinations(sorted(y),2)))`

`

Thank you in advance.

### Source code / logs

``

**Comment by devin-petersohn** [comment]
Hi @bkrdmr, thanks for the report!

You are correct, the looping would cause the problem. The source of the problem is that the code turns a distributed object (`dataframe` object) into a non-distributed object (`tuple` via `itertuples`). This incurs a communication overhead for each iteration of the loop.

We are working on a query optimizer that can optimize the content of loops over `iterrows`/`itertuples`, but appending these values to a Python list would be impossible to do in parallel. At some point there would be a communication bottleneck to build the list.

One option to keep everything as parallel as possible in the current version of Modin:

```python
parallel_list = gp.apply(lambda s: [] if len(s.iloc[1]) <= 1 else list(combinations(sorted(s.iloc[1], 2))), axis=1)
edges = [element for list_val in parallel_list.to_list() for element in list_val]  # Convert the whole thing to a list at once rather than build 1 item at a time
```
I can't test this, but I think it's pretty close to what you would need to be able to take advantage of the parallel operations to build the Python list you're looking for.

**Comment by RehanSD** [comment]
Hi @bkrdmr! Hopefully Devin's code snippet should resolve this issue - if not, feel free to reopen this issue, or open a new one!
