### ISSUE TITLE
Improve CI performance with xdist pytests

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#3031]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?

All tests currently executed on GitHub Actions work in single process. This is not optimal since even free GA workers contain 2 CPU cores, so we could speed up CI tasks at least 2x times. More speedup may be possible if we utilize our own GA workers with more CPU cores.

**Comment by gshimansky** [comment]
Windows on Ray tests fail because of Ray bug https://github.com/ray-project/ray/issues/13213

**Comment by vnlitvinov** [comment]
We definitely need this for Windows CI to stop randomly failing, as it now seems to be hitting timeout time and again randomly.

**Comment by devin-petersohn** [comment]
The timeouts are due to issues in the Dask engine, I believe. We added a timeout because the default timeout of 6 hours was always getting hit. I think there's an underlying issue that I haven't reproduced locally, but I don't think this would solve the timeout issue. cc @YarShev who worked with me to add the timeout in the first place

**Comment by vnlitvinov** [comment]
I was referring to timeouts in running Ray tasks, but whenever we lessen CI run time the better :)

**Comment by gshimansky** [comment]
I noticed that `test_io.py` when it successfully finished on windows was very close to its timeout of 20 minutes, so I increased it to 30 minutes in this fix too.
