### ISSUE TITLE
Modin's `DataFrame.apply` computes result type incorrectly

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3219]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Modin version** (`modin.__version__`): 027e1fba53286bf8b7ceccd11b8c6d04ff5b9ab3
- **Python version**: 3.7.5
- **Code we can use to reproduce**:
```python
import modin.pandas as pd

df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

pd_res = df._to_pandas().apply(lambda row: row["a"] + row["b"], axis=1)
md_res = df.apply(lambda row: row["a"] + row["b"], axis=1)

print(f"Pandas result:\n{type(pd_res)}\n{pd_res}\n")
print(f"Modin result:\n{type(md_res)}\n{md_res}")

```

<details><summary>Output</summary>

```
Pandas result:
<class 'pandas.core.series.Series'>
0    5
1    7
2    9
dtype: int64

Modin result:
<class 'modin.pandas.dataframe.DataFrame'>
   __reduced__
0            5
1            7
2            9

```

</details>

### Describe the problem
The expected result in the case of reduction apply along 1 axis is unnamed Series, but Modin produces Series-like DataFrame

**Comment by mvashishtha** [comment]
For the example in the first comment, I confirmed that [this code](https://github.com/modin-project/modin/blob/ef2159be59194891304f89fe5be15a03214d0e7b/modin/pandas/dataframe.py#L373) is determining the output type. It creates an empty dataframe with the same columns as the original one, runs apply on it, and uses the type that Pandas outputs. However, in this case, Pandas does indeed return a dataframe, so Modin's final return type is a dataframe. Here's whats happening in detail:

```
import modin.pandas as pd
df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
empty_df =  pandas.DataFrame(columns=df.columns)
empty_df.apply(lambda row: row["a"] + row["b"], axis=1)
```

You can see the result is an empty dataframe, not a series:

```
Empty DataFrame
Columns: [a, b]
Index: []
```

OTOH, the linked code works for the case where we apply a function mapping each column to a scalar, reducing the dataframe to a series:

```
import modin.pandas as pd
df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
empty_df =  pandas.DataFrame(index=df.index)
empty_df.apply(sum, axis=0)
```

The result is a Series:

```
Series([], dtype: float64)
```

Going back to the Dataframe problem in this bug, I suppose Pandas can't determine the return type of apply() until it calls the function: if the function returns a scalar, the result should be a Series, but if it returns a Series, or it returns a list and the `result_type` argument to `apply` is `expand`, the result should be Dataframe. So I don't think our current method of determining the output type will work. I tried always using [this line](https://github.com/modin-project/modin/blob/ef2159be59194891304f89fe5be15a03214d0e7b/modin/pandas/dataframe.py#L391) instead of deducing the type as we do now, but I broke many tests. What alternatives are there?

I'm on modin version `0.11.1+32.gef2159be`

**Comment by devin-petersohn** [comment]
@dchigarev I think the question in the previous comment is for you.

**Comment by YarShev** [comment]
@vnlitvinov, you might be a good person to help since you recently dealt with this or something similar.

**Comment by vnlitvinov** [comment]
I think we should follow the logic of this fix https://github.com/modin-project/modin/pull/3580 and do the same for `DataFrame.apply()` - i.e. to use a one-row DataFrame (if `axis=0`) or one-column (if `axis=1`) fed to the real user function to determine the output if `result_type==None`.

**Comment by dchigarev** [comment]
@mvashishtha 

Basically, we imply that the executor (backend) knows about the return type of passed function (since it executes it and places the results in the QC), that's why we can assume that the QC may be a source of information about the return type.

Speaking about the only Modin's backend that supports `apply` (pandas), it returns a QC with the `"__reduced__"` columns if the passed function's output type was a scalar and so the frame's result type has to be a Series. The flow of getting such results is the following: 
1. ModinFrame applies a passed function to `pandas.DataFrame`s representing each of the AxisPartition, since it's a pure pandas objects, the behaviour match pandas: a Series is returned.
2. Partition can't store Series and so converts it into a DataFrame with `["__reduced__"]` columns
3. `["__reduced__"]` columns are propagated to the DataFrame API layer where we can use it to deduce the output frame's type.

This behavior is of course pandas backend specific, but since for now, there are no other backends that support `apply(python_function)` we can assume (or better write it to the `QC.apply` docstring) that all of the backends return a QC with the `["__reduced__"]` labels if the passed python function returns scalars. If this assumption is made, we can return a Series in `apply` whenever labels of the applied axis became `__reduced__`.

I've tried this approach in a separate branch in [this commit](https://github.com/dchigarev/modin/commit/ef82e56089ec54d302efd2bc35a7243a6b6b155f) and all of the existing tests as well as the newly added case from the reproducer seems to pass.

If we're all okay with this approach I can create a PR from this branch.

**Comment by YarShev** [comment]
@dchigarev , please open a PR. It is always better to discuss the changes in PRs but not in separate branches.
