### ISSUE TITLE
Why we need dask and other engine?

### ISSUE THREAD

**Issue by DonYum** [modin-project/modin#3268]
As I understand, modin on ray is faster and more flexible then modin on dask, and Ray is good enough, so, why introduce Dask or other engine?

**Comment by romainRoch** [comment]
Dask is used mostly for the Windows users. Stick with Ray and uninstall Dask if it bothers you !
As other engines, it seems that there are none, believing the documentation.

**Comment by devin-petersohn** [comment]
@romainRoch is correct that Dask is better on Windows, but there are a couple of other reasons for Dask and other engines:

1.) We want Modin to run on what you have available. Modin users can keep the same notebook, and the underlying Modin orchestration system will detect and use the compute engine available. If you only have Dask available to you, we did not want that to be a blocker for using Modin. If you need to switch back and forth, that shouldn't be a problem either. Everything will still work (just maybe not as fast).

2.) Different engines are good at different things. We have work toward an Omnisci engine, which is a fast in-memory jit-compiled database. It isn't able to do everything in pandas (because of the differences in dataframes and databases, detailed here: https://arxiv.org/pdf/2001.00888), but what it can do, it does very fast. Some queries in Modin have historically been faster on Dask than Ray, but ultimately we want users to use what they're comfortable with.

It's a great question, hopefully this helps!

**Comment by DonYum** [comment]
Thanks a lot for your reply.
Is there any benchmark for the performance of modin on ray and dask.
BRs!

**Comment by RehanSD** [comment]
@vnlitvinov I know you are currently investigating Dask performance - would you be able to post any benchmarks here?

**Comment by anmyachev** [comment]
Looks outdated.

At the moment we only have performance [results](https://modin.org/modin-bench/#/) for modin on ray and modin on hdk.
