### ISSUE TITLE
Network access

### ISSUE THREAD

**Issue by adconn** [modin-project/modin#3297]
Hi,

I am wanting to run Modin with Dask on windows, and windows firewall pops up asking to allow it through the firewall.

Question:
- Is modin / dask communicating with a server?
- Or is it local only?

**Comment by devin-petersohn** [comment]
Hi @adconn thanks for the questions!

>Is modin / dask communicating with a server? Or is it local only?

No, the way that Dask handles communication between local workers is the same way that it would remote workers, but you can turn off your internet and it will not impact functionality at all. It's because of the communication protocol, not any communication with the outside. It is local only unless you connect to a Dask cluster somewhere else (not common). 

Does that make sense? It's a reasonable question!

**Comment by adconn** [comment]
That makes sense. My concern is because I don't want data on this project being transmitted outside of my local pc.

If I use the simple method (just importing modin.pandas as pd) I should be ok?

**Comment by devin-petersohn** [comment]
@adconn That is correct, nothing will be transmitted. Modin does not connect to the internet, and we only use Dask to execute tasks and communicate between workers. Dask uses ports to communicate, which is why the warning comes from Windows. Ray is no different in that respect.

**Comment by anmyachev** [comment]
Answered in https://github.com/modin-project/modin/issues/3297#issuecomment-889221952 and https://github.com/modin-project/modin/issues/3297#issuecomment-889231302
