### ISSUE TITLE
Passing a modin dataframe to the pandas dataframe constructor discards rows and/or columns

### ISSUE THREAD

**Issue by smacke** [modin-project/modin#3361]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.5
- **Modin version** (`modin.__version__`): 0.10.1
- **Python version**: 3.7.11
- **Code we can use to reproduce**:

```
import modin.pandas as md_pd
import pandas as pd
df = md_pd.DataFrame({'x': [0, 1, 2], 'y': [1, 2, 3]})
pd.DataFrame(df)
```
```
   0
0  x
1  y
```

### Describe the problem
Seems like passing a modin dataframe to the pandas dataframe constructor discards some stuff for some reason.

**Comment by dchigarev** [comment]
This happens, because `pandas` treat modin DataFrame as an iterable object, and so tries to extract the values via the default frame's iterator, the thing is the basic iterator just enumerates columns, not the frame's data, this is the expected behaviour:
```python
>>> df = pandas.DataFrame({"a": [1, 2], "b": [3, 4], "c": [5, 6]})
>>> for x in df:
...     print(x)
...
a
b
c
```
The proper way to convert modin frame to pandas is to use utility function [`to_pandas`](https://github.com/modin-project/modin/blob/0bc409d6ae294986db5f7db19d082622544fb122/modin/utils.py#L364) from the `modin.utils`, the modified code above would look like this:
```python
import modin.pandas as md_pd
from modin.utils import to_pandas

import pandas as pd

df = md_pd.DataFrame({'x': [0, 1, 2], 'y': [1, 2, 3]})
pd_df = to_pandas(df)
print(pd_df)

# Output:
#    x  y
# 0  0  1
# 1  1  2
# 2  2  3
```
If the reason for conversion to pandas is to execute a single operation that is slower or not supported in modin, then you can use the [`_default_to_pandas`](https://github.com/modin-project/modin/blob/0bc409d6ae294986db5f7db19d082622544fb122/modin/pandas/base.py#L428) method of the modin DataFrame. This will convert modin frame to pandas, execute passed function and convert pandas result back to modin:
```python
import modin.pandas as pd
import pandas

md_df = pd.DataFrame({'x': [0, 1, 2], 'y': [1, 2, 3]})
res = md_df._default_to_pandas(pandas.DataFrame.quantile, q=0.4)
print(type(res))
print(res)

# Output:
# UserWarning: `DataFrame.quantile` defaulting to pandas implementation.
# To request implementation, send an email to feature_requests@modin.org.
# <class 'modin.pandas.series.Series'>
# x    0.8
# y    1.8
# Name: 0.4, dtype: float64
```
You can find more about defaulting to pandas at the [modin's docs](https://modin.readthedocs.io/en/latest/supported_apis/index.html#defaulting-to-pandas)

**Comment by anmyachev** [comment]
Solution: https://github.com/modin-project/modin/issues/3361#issuecomment-903660482
