### ISSUE TITLE
How to pass the sqlalchemyconnection string for oracle modin read_sql

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#3400]
Comes from https://stackoverflow.com/questions/68999218/how-to-pass-the-sqlalchemyconnection-string-for-oracle-modin-read-sql.

**Comment by YarShev** [comment]
cc @amyskov

**Comment by amyskov** [comment]
Currently modin `read_sql` doesn't support SQLAlchemy or another object connectables, so `con` parameter should be passed as string. Connection string looks correct, so, i think, we need more details about this case (can reproducer be provided or does it work on `pandas.read_sql`?).

**Comment by OBINJAWED** [comment]
I'm having the same issue as the poster. In my case, pandas.read_sql works and when I try using modin.pandas with pd.read_sql, I get the following message:

"UserWarning: To use parallel implementation of `read_sql`, pass the sqlalchemyconnection string instead of <class 'sqlalchemy.engine.base.Connection'>.
UserWarning: Parameters provided defaulting to pandas implementation."

Can I have an example of how to pass the sqlalchemyconnection string to pd.read_sql?

**Comment by mvashishtha** [comment]
I'm reopening this issue so I can respond to @YarShev  comments on #3629.
