### ISSUE TITLE
ASV on successive launches, saves the latest version of the shapes in a separate file.

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3401]
This effect is observed due to shapes that defined by the environment variable `MODIN_BACKEND` which in turn leads to the fact that different forms can be used from time to time.

Example:
`MODIN_BACKEND=omnisci MODIN_EXPERIMENTAL=true asv run ... -b ^omnisci ...`
`asv run ... -b ^benchmarks ...` In this case, the shapes will replace the previous ones `(Old: [[1_000_000, 10]] -> New: [[5000, 5000], [1_000_000, 10]])`

**Comment by dchigarev** [comment]
I didn't quite get the sense of the issue. As I understood:
```
MODIN_BACKEND=Omnisci asv run -b "omnisci.unary_op_benchmark"
```
Will use [`[10_000, 10]` shape](https://github.com/modin-project/modin/blob/b68c89bfb242f3709b4a8cc552b7b3b04b4f2ff8/asv_bench/benchmarks/utils/data_shapes.py#L70-L72), because the OmniSci backend was picked, and so [this if-statement](https://github.com/modin-project/modin/blob/b68c89bfb242f3709b4a8cc552b7b3b04b4f2ff8/asv_bench/benchmarks/utils/data_shapes.py#L88-L92) will route us to the OmniSci-tunned dataset sizes.

If we run the following:
```
asv run -b "non_omnisci.unary_op_benchmark"
```
We'll get [`([250, 250], [10_000, 10])` shapes](https://github.com/modin-project/modin/blob/b68c89bfb242f3709b4a8cc552b7b3b04b4f2ff8/asv_bench/benchmarks/utils/data_shapes.py#L43-L46) because now `MODIN_BACKEND=Pandas` (default value). Could you please elaborate the problem?

**Comment by anmyachev** [comment]
After the first launch of a subset of benchmarks, some parameters are recorded in the file, after the second launch of another subset, all benchmarks are overwritten at once.

The problem is that the same class can have different parameters depending on the environment variable.

`MODIN_BACKEND=Omnisci asv run -b "omnisci.unary_op_benchmark"` - will write `[10_000, 10]` shape for `"omnisci.unary_op_benchmark"`

`asv run -b "non_omnisci.unary_op_benchmark"` - will write `([250, 250], [10_000, 10])` shape also for `"omnisci.unary_op_benchmark"`. Each time ASV creates a file where **all** benchmarks with parameters are recorded.

**Comment by dchigarev** [comment]
> `asv run -b "non_omnisci.unary_op_benchmark"` - will write `([250, 250], [10_000, 10])`

actually should be `asv run -b "omnisci.unary_op_benchmark"`? Otherwise, why would ASV write data for the `"omnisci.unary_op_benchmark"` if the names of benchmarks are different? Or it relies only on the benchmark's class name which is `unary_op_bencmmark`? If so, how does #3402 fix this issue?

**Comment by anmyachev** [comment]
Just try to run any benchmark after deleting `asv_bench\.asv\results\benchmarks.json`.

After launch, this file will automatically appear in the same place. Inside it will be information about all the benchmarks, not just the one you ran.
