### ISSUE TITLE
The subset filter is slow

### ISSUE THREAD

**Issue by lw3259111** [modin-project/modin#350]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
redhit
- **Modin installed from (source or binary)**:
github
- **Modin version**:
2.0.5
- **Python version**:
3.6.2
- **Exact command to reproduce**:

### Describe the problem

The filter is very slow,
```
old pandas
 %time data = data[data['FILTER']=="PASS"]
CPU times: user 24 s, sys: 2.92 s, total: 26.9 s
Wall time: 26.4 s

modin pandas
%time data = data[data['FILTER'].str.contains("PASS")]
W0102 13:37:16.832880 29990 node_manager.cc:243] Last heartbeat was sent 4481 ms ago
```
the modin pandas can't finished the command.

**Comment by devin-petersohn** [comment]
This part of the command `data['FILTER'].str.contains("PASS")` is going to take some time. Because we are still working on a distributed Series, this object will be collected and run on a single-core. This is what is taking time.

The error message you see is coming from Ray:
```
W0102 13:37:16.832880 29990 node_manager.cc:243] Last heartbeat was sent 4481 ms ago
```
This may mean that you do not have enough memory for the workload you are trying. If you have a lot of intermediate dataframes or objects, this could be the solution. We have some solutions planned for this problem, but for now they are not fully implemented yet.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
