### ISSUE TITLE
Usage of LIMIT clause to fetch column names incompatible with sql server

### ISSUE THREAD

**Issue by pointerness** [modin-project/modin#3524]
### System information
- **OS Platform and Distribution (Windows 10 Enterprise (10.0))**:
- **Modin version** (0.11.0`):
- **Python version**:3.9.5
- **Sql Server version**: Microsoft SQL Server Express (64-bit) version 15.0.2000.5
- **Code we can use to reproduce**:

### Describe the problem

Modin uses Limit to get column names. This is not standard sql and is not supported by sql server.
Sql_dispatcher.py line number 85
        cols_names_df = pandas.read_sql(
            "SELECT * FROM ({}) as foo LIMIT 0".format(sql), con, index_col=index_col
        )

The sql produced by the above line throws an error when used with sqlalchemy connection string.
ERROR 2021-10-07 14:16:37,560 17756 21468 apriori.py get_recommendation 278  <class 'sqlalchemy.exc.ProgrammingError'> (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'LIMIT'. (102) (SQLExecDirectW)")
[SQL: SELECT * FROM ({sql_query}) as foo LIMIT 0]

**Comment by martinpmsmith** [comment]
Any news on an implementation or ETA for this ?

**Comment by devin-petersohn** [comment]
Hi @martinpmsmith thanks for checking in, and thanks for posting the potential solution!

One of the challenges is that we need to generate different SQL depending on the database. The second challenge is that we need to set up a testing environment for each of these databases. Pandas does not test SQL Server, for example, but we would need to test SQL Server specifically (as well as others) because we are generating code specifically for these database systems.

I'm happy to accept a PR, but so far have been working to get a test environment set up so that we can make sure an implementation is correct. Does that make sense?

**Comment by YarShev** [comment]
Should this be closed in #4279?

**Comment by mvashishtha** [comment]
Yes, #4279 resolves this issue.
