### ISSUE TITLE
Pandas doesn't work paralell

### ISSUE THREAD

**Issue by rd5802** [modin-project/modin#376]
Hi,

Pandas dataframe seems to work in a single thread (defaults). Is it sth specific to Python 3.7?
Redis server is not avalable under givend URL.
Regrds,
Rafal

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.1 LTS as Virtualbox Windows 10 guest
- **Modin installed from (source or binary)**: pip install modin, pip install setproctitle
- **Modin version**: 0.2.5
- **Python version**: 3.7
- **Exact command to reproduce**:

`import modin.pandas as pd`
`import numpy as np`

`frame_data = np.random.randint(0, 100, size=(2**10, 2**8))`
`df = pd.DataFrame(frame_data)`

`Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-01-04_20-09-46_4335/logs.
Waiting for redis server at 127.0.0.1:53534 to respond...
Waiting for redis server at 127.0.0.1:59945 to respond...
Starting the Plasma object store with 3.3455915 GB memory using /dev/shm.`

`df`

`df.to_csv('ddd.csv')`

`/home/rafal/anaconda3/lib/python3.7/site-packages/modin/pandas/dataframe.py:3964: UserWarning: Defaulting to Pandas implementation
  warnings.warn("Defaulting to Pandas implementation", UserWarning)`

**Comment by devin-petersohn** [comment]
Hi @rd5802,

Some operations are always single-threaded because we default to the pandas implementation (see [documentation](https://modin.readthedocs.io/en/latest/pandas_supported.html)). `df.to_csv(...)` is one of these operations because parallel writes to a single file are not easy to coordinate.

Are there other operations you are having problems with? I am in the process of doing a performance tuning round of improvements, so if you have anything you would like me to look into, please let me know.

**Comment by devin-petersohn** [comment]
To get to your point about Python 3.7, no there are no specific defaults for 3.7 over 3.6. 

If your question is regarding the `pd.DataFrame(frame_data)` part of your code, see this question/answer (#232)

**Comment by rd5802** [comment]
Thanks Devin. That closes this issue.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
