### ISSUE TITLE
insert a column to an empty dataframe gets "Length of values does not match length of index" error

### ISSUE THREAD

**Issue by eavidan** [modin-project/modin#381]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin installed from (source or binary)**: binary
- **Modin version**: 0.2.5
- **Python version**: 3.6.4
- **Exact command to reproduce**: snippet below

### Describe the problem
Dataframe().insert fails with "Length of values does not match length of index" when trying to insert a column to an empty dataframe. A reindex of the axis should probably be done according to the new column in case the dataframe does not have an index yet

### Source code / logs

```
# works

import pandas as pd

df = pd.DataFrame()
df['x'] = [1, 2, 3]
print(df)

# does not work

import modin.pandas as pd

df = pd.DataFrame()
df['x'] = [1, 2, 3]
print(df)
```

**Comment by devin-petersohn** [comment]
@eavidan Thanks for finding this! You are correct that if the index is empty we just need to do a `reindex`. This one should be fairly straightforward, so I'll mark as good first issue.

**Comment by devin-petersohn** [comment]
I also tested this on current master and it is still there. we have been doing a lot of error checking on real-world workflows lately, and this is something we should definitely support.

**Comment by eavidan** [comment]
This is actually how I encountered it. I am working on moving one of our packages which uses pandas to use modin. Will fix this and submit a PR

**Comment by eavidan** [comment]
@devin-petersohn what would be the correct way to do this?
should we pipe the reindex to the insert function and submit both to the query compiler? can this be done?
or should we update in place the reindex if necessary and then submit the insert?

**Comment by devin-petersohn** [comment]
`reindex` in `insert` probably would not work. `insert` only submits a function to the partition that it is inserting into. `reindex` first makes sense, but this can probably be done on the `DataFrame.insert` side in dataframe.py. It should all be able to be done in that layer.

This is how I would recommend doing it (no promises on it working right away 😄):

```python
def insert(...):
...
    if len(self.index) == 0:
        new_index = pandas.RangeIndex(len(value))# (logic to find new index -- in list case it is RangeIndex)
        new_columns = self.columns # In case there are already columns
        new_query_compiler = DataFrame(index=new_index, columns=new_columns)._query_compiler.insert(...)
    else:
# Rest of insert logic
....
```

That will do the "reindex" operation by creating a new DataFrame. The only real problem with that would be if there are already a lot of columns but no index, but I think we can solve that edge case separately. This is a few lines of code and doesn't go through `reindex` which could be incorrect.

**Comment by eavidan** [comment]
thanks @devin-petersohn 
this approach does solve the index error issue (the reindexing works), but now I encounter an issue with the insert operation.
When the query compiler executes the insert method, is has a call to `apply_func_to_select_indices_along_full_axis` (block_partitions.py)
```py
new_data = self.data.apply_func_to_select_indices_along_full_axis(
            0, insert, loc, keep_remaining=True
        )
new_columns = self.columns.insert(loc, column)
return self.__constructor__(new_data, self.index, new_columns)
```py
Since the data frame is empty, it returns an empty array:
```py
if self.partitions.size == 0:
    return np.array([[]])
```
This (I think) causes the `return self.__constructor__(new_data, self.index, new_columns)` to fail with 
```py
assert isinstance(block_partitions_object, BaseBlockPartitions)
```
all this does not happen if the data frame has some columns to begin with, only when it's empty.
any suggestions on how I can fix this?

**Comment by devin-petersohn** [comment]
Yes, we have an optimization that frees empty partitions, which would mean that the partitions in `BlockPartitions` would be empty. ([link](https://github.com/modin-project/modin/blob/master/modin/engines/base/block_partitions.py#L57-L81))

We don't actually need to use `insert`. We can just pass the `value` to the `DataFrame` constructor.

Similar to above:

```python
def insert(...):
...
    if len(self.index) == 0:
        new_index = pandas.RangeIndex(len(value))# (logic to find new index -- in list case it is RangeIndex)
        new_columns = self.columns.insert(loc, column) # In case there are already columns
        new_query_compiler = DataFrame(value, index=new_index, columns=new_columns)
    else:
# Rest of insert logic
....
```

This way, we automatically partition it via the constructor (which is fairly well optimized) instead of using `insert`. This also allows us to keep our optimizations related to freeing empty partitions from the memory pool. It is also cleaner! 

Thanks again for taking this one on. Let me know if there are any other questions you have.

**Comment by devin-petersohn** [comment]
Closing via #398. Thanks @eavidan!

**Comment by linehammer** [comment]
The ValueError: Length of values does not match [length of index](http://net-informations.com/ds/err/length.htm) raised because the previous columns you have added in the DataFrame are not the same length as the most recent one you have attempted to add in the DataFrame. So, you need make sure that the length of the array you are assign to a new column is equal to the length of the dataframe .

The simple solution is that you first convert the list/array to a pandas Series , and then when you do assignment, missing index in the Series will be filled with NaN values .
