### ISSUE TITLE
test_general.py fails to import modin_spreadsheet

### ISSUE THREAD

**Issue by jeffreykennethli** [modin-project/modin#3918]
### System information
- **OS Platform and Distribution:** Linux Ubuntu 20.04.3
- **Modin version** : 0.12.0
- **Python version**: 3.8
- **Code we can use to reproduce**: [test run](https://github.com/modin-project/modin/runs/4764527263?check_suite_focus=true)
- 
### Describe the problem
test_general.py fails to import modin_spreadsheet, failing because the decorator [widget.register() in grid.py](https://github.com/modin-project/modin-spreadsheet/blob/master/modin_spreadsheet/grid.py#L558) is missing a positional argument "widget", from this [function decorator](https://github.com/jupyter-widgets/ipywidgets/blob/master/python/ipywidgets/ipywidgets/widgets/widget.py#L250-L260) in ipywidgets.

### Source code / logs
<img width="800" alt="Screen Shot 2022-01-10 at 12 18 36 PM" src="https://user-images.githubusercontent.com/15958254/148809551-d728c776-6ce5-442a-8858-d73e3d5c01f5.png">

**Comment by vnlitvinov** [comment]
@jeffreykennethli could you please provide with a step-by-step repro here?

**Comment by mvashishtha** [comment]
It looks like some version of `ipywidgets` that disallowed `widget()` with no arguments came out, and then went away, then came back. This should be fixed by #4838.

test_general.py is [passing](https://github.com/modin-project/modin/runs/8073656491?check_suite_focus=true) at master with (AFAIK) no skip added to cover this failure, so I think we're good
