### ISSUE TITLE
Ability to disable warnings

### ISSUE THREAD

**Issue by denish44** [modin-project/modin#3935]
Could we have some way to disable warnings that modin prints out (maybe through the config module) when it switch between pandas/modin for certain functionality and other warnings.

**Comment by mvashishtha** [comment]
@denish44 thank you for bringing up this issue. You can use [ `warnings.filterwarnings`](https://docs.python.org/3/library/warnings.html#warnings.filterwarnings) to ignore all warnings from the Modin module. For example, you can write:

```python
import modin.pandas as pd
import warnings
warnings.filterwarnings('ignore', module='modin')
pd.DataFrame()
```

Normally, constructing the Modin dataframe in the last line would give you the warning 

`UserWarning: Distributing <class 'NoneType'> object. This may take some time.`

but because of the warning filter, you should not get the warning.

Does that solution work for you?

**Comment by denish44** [comment]
I believe that should work for us. Thanks
