### ISSUE TITLE
MultiIndex: DataFrame.loc with a tuple on columns defined as MultiIndex returns an error

### ISSUE THREAD

**Issue by neltacigreb** [modin-project/modin#4358]
### System information
- **OS Platform and Distribution**: MacOS Monterey 12.2.1
- **Modin version** 0.14
- **Python version**: 3.8.12
- **Code we can use to reproduce**:

### Using modin: 
```python
import ray
ray.init()
import modin.pandas as pd
import numpy as np

arrays = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"],
]
columns =  pd.MultiIndex.from_tuples(zip(*arrays), names=['a', 'b'])
data = [np.random.randint(10, 50, len(columns)) for _ in range(30)]
df = pd.DataFrame(data, columns=columns)

# bug happens here
df.loc[:, ("bar", "two")]
```

### Same operation in vanilla pandas 
```python
import pandas as pd
import numpy as np

arrays = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"],
]
columns =  pd.MultiIndex.from_tuples(zip(*arrays), names=['a', 'b'])
data = [np.random.randint(10, 50, len(columns)) for _ in range(30)]
df = pd.DataFrame(data, columns=columns)

df.loc[:, ("bar", "two")]
```

### Describe the problem
When using .loc with tuples on a multiIndex, a ValueError appears

### Source code / logs
**traceback:**
```shell
Traceback (most recent call last):
  File "/VIRTUALENV/lib/python3.8/site-packages/ipython-7.32.0-py3.8.egg/IPython/core/interactiveshell.py", line 3524, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-59ea95655168>", line 1, in <cell line: 1>
    df.loc[:, ("bar", "two")]
  File "/VIRTUALENV/lib/python3.8/site-packages/modin/pandas/indexing.py", line 674, in __getitem__
    result.columns = result.columns.droplevel(list(range(len(col_loc_as_list))))
  File "/VIRTUALENV/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2063, in droplevel
    return self._drop_level_numbers(levnums)
  File "/VIRTUALENV/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2074, in _drop_level_numbers
    raise ValueError(
ValueError: Cannot remove 2 levels from an index with 2 levels: at least one level must be left.
```

**Comment by neltacigreb** [comment]
It will however work when explicitely converting the tuple to a MultiIndex: 

```python
df.loc[:, pd.MultiIndex.from_tuples([ ("bar", "two")])]
```

**Comment by mvashishtha** [comment]
@neltacigreb thank you for the detailed bug report. I reproduced the issue with your code on Modin commit 6d05c31a24da9776723a179c74b70338b9302a82.

The bug happens when the column selectors in the `loc` select one column at each level of the column MultiIndex. Modin needs to stop trying to drop all levels of the result `DataFrame` [here](https://github.com/modin-project/modin/blob/e5e9634357e60925a5a70e56a1d4882d269f533a/modin/pandas/indexing.py#L674). Instead, Modin should make a `Series` whose name comes from the columns selected, e.g. in the example pandas snippet above, the Series name is `('bar', 'bars')`. I guess we should make `_LocationIndexerBase. __getitem__` return a `Series` with the correct column name in this case.

**Comment by pyrito** [comment]
I tried taking a stab at this bug and was able to trace it down for this specific case which is basically what @mvashishtha was able to triage. The axis we squeeze the resulting DataFrame is incorrect and causes some issues (in `__getitem__` in the base indexer). However, while we can come up with a basic fix for now, it's become clearer that the behavior for MultiIndexes is a bit more complicated than we would like to think. Here's a motivating example of some unclear behavior:
```python
df = pd.DataFrame([1, 2], index=[['a', 'a'], ['b', 'b']])
df.loc[('a', 'b'), 0])
```
The issue here is that we have duplicates in the MultiIndex and this causes `loc` to return the correct DataFrame in the intermediate representation. However, the rest of our code tries to incorrectly drop levels, leading to the same error. We see in this current issue. 

 I'm hesitant to merge in a fix that will add more spaghetti code in our code base and I'd prefer that we have some further discussion about the MultiIndex case. Thoughts? @modin-project/modin-core @modin-project/modin-contributors

**Comment by pyrito** [comment]
I think it's better to show rather than tell, so folks can take a look at what I tried in this draft PR: https://github.com/modin-project/modin/pull/4608
