### ISSUE TITLE
Make use Ray back from conda-forge in CI

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#4381]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`):
- **Python version**:
- **Code we can use to reproduce**:

### Describe the problem

Reverting #4364, hopefully new Ray works ok now

**Comment by devin-petersohn** [comment]
I prefer to use Ray from pip in CI. That is how most users will install and I prefer to test that case.

If we want to add tests on Ray from conda, that is fine, but I don't want to replace the ray from pip tests

**Comment by YarShev** [comment]
Our env files have become different in terms of packages discrepancy to be installed. We should have a file (`requirements-dev.txt`) using which we would install packages from PyPI. Also, we should have a file (`environment-dev.yml` and related ones) using which we would install packages from conda channels and the packages from PyPI, which are not present in conda channels. Since packages are mostly uploaded in PyPI first, maybe we should move our testing to `requirements-dev.txt` usage. And, of course, we should fix env*.yml files to provide packages installation without an error. Does that make sense?

**Comment by prutskov** [comment]
> Our env files have become different in terms of packages discrepancy to be installed. We should have a file (`requirements-dev.txt`) using which we would install packages from PyPI. Also, we should have a file (`environment-dev.yml` and related ones) using which we would install packages from conda channels and the packages from PyPI, which are not present in conda channels. Since packages are mostly uploaded in PyPI first, maybe we should move our testing to `requirements-dev.txt` usage. And, of course, we should fix env*.yml files to provide packages installation without an error. Does that make sense?

Possible, it will be better to test the both of environment sources (`requirements-dev.txt`/`environment-dev.yml`). We can split our testing workflows to run the one part of testing on PyPI env, the other on conda env.

**Comment by RehanSD** [comment]
I personally prefer a requirements.txt file since I've had trouble installing ray from conda, but perhaps we could adopt a hybrid approach? Perhaps have a pip-requirements.txt that specifies packages that we only ever install via pip, and then have an env.yaml that links to that file [like so](https://stackoverflow.com/a/59056234), and a requirements.txt file that contains the same packages as the env.yaml file and links to the pip-requirements.txt file [like this](https://stackoverflow.com/a/63898125)?

It's a bit complicated, but it does mean that the conda and pip installs will have parity across pip packages (since we change the one file and it changes for both), as well as that users can use one file to install via their preferred package manager.

**Comment by YarShev** [comment]
I don't think this is the best option because we should be testing Modin both with pypi packages and conda packages. I think we should test the entire scope of Modin with requirements.txt, as well as with environment.yml for at least one test suite.

**Comment by vnlitvinov** [comment]
Same here, especially given Ray guys started (again) to pay some attention to conda forge.

I think we should at least have a job of "install all from conda and try running something", as now we aren't testing `conda install modin-all` scenario at all

**Comment by anmyachev** [comment]
Ray already used from conda-forge.
