### ISSUE TITLE
ProgressBar for `.apply` when looping over rows

### ISSUE THREAD

**Issue by Bonnevie** [modin-project/modin#4443]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.4 LTS
- **Modin version** (`modin.__version__`): 0.14.1
- **Python version**: 3.8
- **Code we can use to reproduce**:
```python
import modin.pandas as pd
import tqdm
from modin.config import ProgressBar
ProgressBar.enable()

X = pd.DataFrame([[1,2,3]]*100, columns=["a", "b", "c"]) # be wary that this produces its own progress bar
X.apply(lambda x: 1, axis=1) # does not produce progress bar; if axis=0, progress bar is produced
```

### Describe the problem

The `ProgressBar` seems to not appear when `apply` is used with `axis=1` (iterating over rows). It does appear for `axis=0`, but oddly not if a `Series` is returned (common pattern for constructing new dataframes). 
If running the example, be careful to disregard the progress bar generated by the `pd.Dataframe` command.

**Comment by mvashishtha** [comment]
@Bonnevie thank you for reporting this issue! I also see the behavior you're describing. I'm investigating what it would take to extend the progress bar to `axis=1` and to `axis=0` functions that return `Series`.

**Comment by jeffreykennethli** [comment]
@Bonnevie 
Thanks for opening this issue! ProgressBar currently works by counting the number of successful Ray remote tasks completed, where each task corresponds to a [Modin Block Partition](https://github.com/modin-project/modin/blob/master/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py). The apply function you declared is a "full-axis" function. To compute these types of functions, Modin converts the Block Partitions to Full Axis Partitions and applies the asynchronously. However, we have not instrumented Full Axis Partitions to report progress, so neither apply with either axis will show the progress of the function.

Confusingly, with `axis=1`, after applying the function on Full Axis Partitions (and converting back to Block Partitions), we need to compute a transpose on each Partition in order to return the column-oriented Partition as a row-wise series (note the result will be a Series with the old columns as the new row index)

```
a 1
b 1
c 1
```
 It is this transpose which is applied to Block Partitions that is being Progress Bar'ed.

TDLR: ProgressBar is not implemented for the type of function you applied (full axis), but is for the transpose applied at the end of a columnar operation. This was a super interesting issue that you raised, and we are now considering adding ProgressBar for full axis operations too.

**Comment by mvashishtha** [comment]
@Bonnevie I would also like to add to @jeffreykennethli 's response:

- Issue #4167 says that we're missing some functions at the internal level of the [Modin dataframe](https://modin.readthedocs.io/en/stable/development/architecture.html). Among those are the ones we would need to give an estimate of `apply` progress. I think just making `apply` work shouldn't be too much effort. I mentioned it in a comment on #4167 and we will try to address the feature soon.
- Each progress bar should tell users which frame-level operation it's for. In the case of `axis=0` apply that you show here, it should explain that it's showing the progress of the transpose. I have filed #4447 for that new feature.

**Comment by mvashishtha** [comment]
@Bonnevie please let us know whether our explanations help. If you understand the behavior you're seeing, I'll close this issue and the Modin contributors will try to address the issues that I mentioned in [my previous comment](https://github.com/modin-project/modin/issues/4443#issuecomment-1121221578).

**Comment by mvashishtha** [comment]
@Bonnevie I'm closing this issue. If you have any more concerns, please comment here. We'll continue tracking work on the followups: https://github.com/modin-project/modin/issues/4443#issuecomment-1121221578
