### ISSUE TITLE
Benchmark Mode blocks on computation so all computation occurs on one node

### ISSUE THREAD

**Issue by RehanSD** [modin-project/modin#4449]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`):
- **Python version**:
- **Code we can use to reproduce**:

### Describe the problem

Since Benchmark Mode calls `wait` on each partition sequentially, computation that can be done in parallel ends up happening sequentially on a single node. We need to instead collect all the OID's of all partitions, and wait on all of them together - that way each of the tasks is kicked off in parallel, and computation happens in parallel.

**Comment by mvashishtha** [comment]
I just want to clarify that the bug applies only when we have a function like a transpose or a reindex that adds a remote function to each partition's call queue, but doesn't trigger the function's execution. In that case, benchmark mode will [trigger](https://github.com/modin-project/modin/blob/c17dde71ae8114723a13279e36bf5532dcba328a/modin/core/dataframe/pandas/partitioning/partition_manager.py#L66) all of the executions serially instead of in parallel.
