### ISSUE TITLE
Warning message: UserWarning: Group indices computation defaulting to pandas implementation. on simple single column groupby

### ISSUE THREAD

**Issue by jaidisido** [modin-project/modin#4459]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: AmazonLinux
- **Modin version** (`modin.__version__`): 0.14.1
- **Python version**: 3.8
- **Code we can use to reproduce**:
```
partition_cols = ["year"]
for keys, subgroup in df.groupby(partition_cols, observed=True):
        subgroup = subgroup.drop(partition_cols, axis="columns")
        keys = (keys,) if not isinstance(keys, tuple) else keys
        ...
```

### Describe the problem

I have a modin dataframe with 10 columns and 18M rows. One of the columns contains "year" values ranging from 1900 to 2020. Running the above code where I do a simple groupby on the year column throws this warning:
```
UserWarning: Group indices computation defaulting to pandas implementation.
```
Why would a simply groupby default to pandas? Note that removing the `observed=True` parameter does not change the warning message.

Perhaps this is similar to this issue (https://github.com/modin-project/modin/issues/1114) where the message is incorrectly displayed?

**Comment by devin-petersohn** [comment]
Hi @jaidisido , thanks for posting!

In this case, the groupby itself is not the problem, but the `for` loop. Looping over groups destroys the parallelism because Modin is unable to parallelism regular Python `for` loops. Is there a way to avoid looping in this case? It is difficult to see from the code you've provided, but happy to help!

**Comment by jaidisido** [comment]
Thanks for the clarification @devin-petersohn, the full code that I am trying to parallelise is [here](https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/s3/_write_dataset.py#L39). I am mostly interested in looping over the keys, not so much the subgroups. Is there a way to obtain those via the groupby without resorting to a for loop? Thanks!

**Comment by RehanSD** [comment]
Hi @jaidisido! Thank you for opening up this issue! I went ahead and looked at the code you linked above, and it seems pretty optimal as far as this computation pattern goes.

Given that the code seems to only require the groupby keys and the rows that correspond to them, I tried another approach - computing the unique values over the partition column (since you mention there's only one groupby key in the issue description) and then looping over those, and computing the dataframe "subgroups" using indexing. 

For both this approach, and the approach in your code, with the following benchmarking code, I found that Modin matched pandas performance. This is on a 10 x 100,000 and 10 x 1,000,000 dataframe on my 2019 Intel Mac! I included a 2 second sleep in each loop to simulate the work being performed in your code.

Performance Benchmark
100K Rows:
| | Modin | pandas |
| -| ------ | ------- | 
| Unique Column Values Loop | 20.62s | 20.09s |
| Groupby Groups Loop | 20.21s | 20.08s |

1M Rows:
| | Modin | pandas |
| -| ------ | ------- | 
| Unique Column Values Loop | 21.57s | 20.54s |
| Groupby Groups Loop | 21.41s | 20.55s |


 100,000 row df on Modin Code:
```python
import modin.pandas as pd
import numpy as np
from time import sleep
shape = (9, 100_000) # We use 9 here since we will add the groupby column (years) in the below line
arr = np.vstack((np.random.randint(1, 1000, shape), np.random.choice(range(1990, 2040, 20), shape[1])))
df = pd.DataFrame(arr)
def col_unique_loop():
    for k in df[9].unique():
        subgroup = df[df[9] == k].drop(9, axis="columns")
        k = (k,)
        sleep(2) # Simulate work
def groupby_loop():
    for k, subgroup in df.groupby(9, observed=True):
        subgroup = subgroup.drop(9, axis="columns")
        k = (k,) if not isinstance(k, tuple) else k
        sleep(2) # Simulate work
from datetime import datetime, timedelta
start_unique = datetime.now()
col_unique_loop()
end_unique = datetime.now()
start_groupby = datetime.now()
groupby_loop()
end_groupby = datetime.now()
print(f"Looping over unique column values took {(end_unique - start_unique) / timedelta(seconds=1)} s")
print(f"Looping over groupby groups took {(end_groupby - start_groupby) / timedelta(seconds=1)} s")
```
To test on 1,000,000 million rows, or on pandas, simple change the import statement or the statement that defines shape!

**Comment by jaidisido** [comment]
Thank you so much @RehanSD, I was able to reproduce this. A couple of follow-up questions if I may before I close the issue:
1. Above tests were limited to a single groupby column. Would the performance significantly change if I was to groupby multiple columns?
2. I am trying to understand the impact on memory of running a groupby in Modin (Ray engine). Are new Ray blocks created as a result of a groupby? If yes, wouldn't that be duplicating memory on the cluster? If not, I am curious to hear what kind of magic Modin does behind the scene to avoid that :)

**Comment by RehanSD** [comment]
Hi @jaidisido 
1. I don't believe performance should be changed.
2. In general, Modin doesn't do operations in place, but looping over a groupby as you're doing above is actually implemented as a series of filter, which is zero copy!
