### ISSUE TITLE
ModuleNotFoundError: No module named 'ray'

### ISSUE THREAD

**Issue by vishalbalaji-v** [modin-project/modin#4617]
I am reopening [this](https://github.com/modin-project/modin/issues/2065) issue as I am facing the same problem.

I'm trying to use Modin on Databricks and getting this error

I've tried both `pip install modin[all]` and `pip install modin[ray]`

Firstly, the installation takes 15 minutes, which is weird.

After installing, I'm doing

```
import modin.pandas as md
df = md.read_parquet('s3://path/to/file')
```

Getting this error
> ModuleNotFoundError: No module named 'ray'

I have also tried setting `os.environ["MODIN_ENGINE"] = "ray" `

**Comment by alejandro-ponder** [comment]
Hi @vishalbalaji-v  - 

thanks for reaching out! Can you provide any more details on the cluster you're trying to do this on? Also, to clarify, it took you 15 minutes to install using `modin[all] `or `modin[ray]` or both?

**Comment by alejandro-ponder** [comment]
I was able to reproduce the slowdown. It seems like databricks is installing multiple older versions of pandas and modin (instead of just the latest) when using the %pip install approach in a notebook. Since this is something very specific to databricks this may be worth raising to the support team there.

The only other path that I can recommend exploring, is rather than installing via the notebook interface, you could try to use a databricks initialization script to install ray and modin as the cluster is started. See this blog post for details on this approach and please let me know if it works: https://databricks.com/blog/2021/11/19/ray-on-databricks.html

**Comment by vishalbalaji-v** [comment]
@alejandro-ponder Actually it seems like the installation is failing while installing a dependency called `blake3`. Is there any way to solve this on Databricks?

```
Collecting blake3
  Using cached blake3-0.3.1.tar.gz (131 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
