### ISSUE TITLE
Fillna doesn't work when series object is an argument

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#4660]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`):
- **Python version**:
- **Code we can use to reproduce**:

```python
import modin.pandas as pd

df = pd.DataFrame({'a': ['a'], 'b': ['b'],}, index=['row1'])
df['c'] = pd.NA
df['c'] = df['c'].fillna(df['b'])   # df['c'].fillna('c') works fine
print(df)
```

### Describe the problem

when fillna is called with series object as argument seems nothing happens while pandas does actual na replacement

**Comment by anmyachev** [comment]
After [this commit](https://github.com/modin-project/modin/commit/8f35ab57996d18f2c1f001d624682952853454cd), `_copartition` function is called in `binary_op` also for columns, which still does reindexing, however, for some functions this action is superfluous, for example, in the case of `fillna`.

Should we make reindexing optional or make a second `_copartition` call optional? cc @prutskov

**Comment by prutskov** [comment]
@anmyachev, according to our patterns of parallel execution partitioning of operands must be aligned by both axis for binary operator (https://modin.readthedocs.io/en/latest/flow/modin/core/dataframe/algebra.html#binary-operator).

The issue @Garra1980 mentioned is reproduced with Modin version before [commit with adding cell-wise execution](https://github.com/modin-project/modin/commit/8f35ab57996d18f2c1f001d624682952853454cd).

The root cause of issue is operation `df['c'].fillna(df['b'])` is performed on separated `Series` objects without full knowledge about the dataframe. The same flow we can reproduce using pandas:

```python
import pandas as pd

df = pd.DataFrame({'a': ['a'], 'b': ['b'],}, index=['row1'])
df['c'] = pd.NA

ser_left = pd.Series([pd.NA], name="c")
ser_right = pd.Series(["b"], name="b")
df['c'] = ser_left.fillna(ser_right)
print(df)
```

So, probably we need to change the implementation of `fillna` for such case.

**Comment by anmyachev** [comment]
> The issue @Garra1980 mentioned is reproduced with Modin version before [commit with adding cell-wise execution](https://github.com/modin-project/modin/commit/8f35ab57996d18f2c1f001d624682952853454cd).

Yes, there is another problem that I know how to fixed. [The problem](https://github.com/modin-project/modin/blob/a7354c9ca76525a265da98f2afe882c53f378840/modin/core/storage_formats/pandas/query_compiler.py#L1876) is that in our internal implementation we use single-column dataframes, which behave differently from the behavior of Series. Some example here:
```python
import pandas as pd

df = pd.DataFrame({'a': ['a'], 'b': ['b'],}, index=['row1'])
df['c'] = pd.NA
print(df['c'].fillna(df['b'])) # works as `df['c']` is a Series in pandas implementation
# attempt to emulate Modin internal behavior
print(df[['c']].fillna(df[['b']])) # all objects here are one-column Dataframes and this's not work
```
Your example isn't working because you need to specify index for Series:
```python
ser_left = pd.Series([pd.NA], name="c", index=["row1"])
ser_right = pd.Series(["b"], name="b", index=["row1"])
```

Apparently the only option left is to make reindexing optional.

**Comment by prutskov** [comment]
> Your example isn't working because you need to specify index for Series:
> 
> ```python
> ser_left = pd.Series([pd.NA], name="c", index=["row1"])
> ser_right = pd.Series(["b"], name="b", index=["row1"])
> ```

Thanks for catch!

> Apparently the only option left is to make reindexing optional.

Could you please describe what "reindexing" do you mean?

**Comment by anmyachev** [comment]
> Could you please describe what "reindexing" do you mean?

`_copartition` calls `_join_index_objects`, which finds the common index to cast the left and right operand to, but for `fillna` doesn't need to do this (this is True for column reindexing). You can see my changes in https://github.com/modin-project/modin/pull/4674.
