### ISSUE TITLE
Column rename operation fails when converting from Modin DataFrame to Ray Dataset

### ISSUE THREAD

**Issue by geoffreyangus** [modin-project/modin#4686]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 12.3.1
- **Modin version** (`modin.__version__`): 0.15.2
- **Python version**: 3.8.13
- **Code we can use to reproduce**: https://gist.github.com/geoffreyangus/5e9fdfd711d9776e76053840fb332274

### Describe the problem

I am attempting to do the following:

1. Convert Modin Series into a Modin DataFrame, while changing the column name using the `to_frame(name="value")`
2. Convert the Modin DataFrame to a Ray Dataset
3. run `map_batches` using the new column name (in this example, "value")
4. Convert the Ray Dataset back to a Modin DataFrame

I am getting an error in step (3) because "value" cannot be found in the Pandas DataFrame objects operated upon in the `map_batches` call.

### Expected Behavior

I expect column name assignment when calling `to_frame(name=<NAME>)`.

Interestingly enough, if the DataFrame is materialized beforehand (using `DataFrame._to_pandas()`), the column name is correctly renamed as a side effect.

### Source code / logs

A minimal repro can be found in the Gist above.

**Comment by mvashishtha** [comment]
@geoffreyangus thank you for reporting this bug. I can reproduce it at Modin da7bd1a14752895a38342b2faa3220a8db4cb7ff. 

The bug is that `from_modin` [calls](https://github.com/ray-project/ray/blob/77e2ef2eb630cb7caa7ca31b3c406b45f8643192/python/ray/data/read_api.py#L835) Modin's `unwrap_partitions`, and Modin's `unwrap_partitions` doesn't apply deferred metadata updates to the modin frame before getting the data. I'll fix that.
