### ISSUE TITLE
PERF: cache loc, iloc, at, iat

### ISSUE THREAD

**Issue by jbrockmendel** [modin-project/modin#4702]
Making these cache_readonly instead of property will give a small perf bump.  xref #4701.

**Comment by mvashishtha** [comment]
@jbrockmendel thanks for filing the issue. How does the caching help? What's an example where it would help? I would be surprised if `modin.pandas.DataFrame.iloc` itself is expensive, because the [`_LocationIndexerBase`](https://github.com/modin-project/modin/blob/eddfda4b521366c628596dcb5c21775c7f50eec1/modin/pandas/indexing.py#L281) object just has references to Modin objects and some bools.

**Comment by jbrockmendel** [comment]
It is not particularly expensive, but it is an easy small win.
