### ISSUE TITLE
'utf-8' codec can't decode byte 0xdc : invalid continuation byte

### ISSUE THREAD

**Issue by chandrabh** [modin-project/modin#4736]
### System information
- **OS Platform and Distribution (e.g., Linux-7)**:
- **Modin version** (`modin.N/A`):
- **Python version**:
- **Code we can use to reproduce**:
requests = os_client.get_object(config['namespace'], config['bucket'], commit_file) #getting from oracle object storage 
pdf = pd.DataFrame(requests.data.content)

### Describe the problem
Not able to read parquet file because it throw error that content is buyte and don't find way to convert it to dataframe using python or spark.

### Source code / logs
ERROR:root:2022-07-29 17:14:33.223916 - Issue in reading source file: sampleout/2022/07/28/projects/ABS/abs-helloworld-shepherd_commits/part-00000-971fce71-ca31-4a13-af5a-aaec4438094e-c000.snappy.parquet Exception is : 'utf-8' codec can't decode byte 0xb0 in position 12: invalid start byte
ERROR:root:Issue in reading source file: sampleout/2022/07/28/projects/AJ/ajcs-terraform_commits/part-00000-d2d7aba0-01a6-4750-97b8-a133725e125d-c000.snappy.parquet Exception is : 'utf-8' codec can't decode byte 0xdc in position 12: invalid continuation byte

**Comment by mvashishtha** [comment]
@chandrabh  thank you for posting your issue here. I have some questions:

- Could you please try to make a code snippet that reproduces a bug? It's not possible to reproduce the bug from the code you shared, because we can't tell what the parquet file looks like at all
- Also, do you get the error in a `read_parquet` call? What does that call look like?
- If you can't share the whole file, could you share just enough to reproduce the bug?
- Are you trying something that works in pandas, but not in Modin?

It will help a lot if you can provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by mvashishtha** [comment]
@chandrabh since you haven't posted any more information in 24 days, I'm going to close this issue as stale. Please comment if you still need help and you can provide more information.
