### ISSUE TITLE
Drop py36

### ISSUE THREAD

**Issue by jbrockmendel** [modin-project/modin#4897]
so we can use `from __future__ import annotations`

**Comment by mvashishtha** [comment]
We recently finished going through a lot of work to support python 3.6 (#4664 and #4147). Originally this was a high priority task because there were lots of Modin downloads at the last Modin version to support python 3.6, 0.8.3.post0 (or before that version came out, 0.8.3). However, according to [pepy.tech](https://pepy.tech/project/modin?versions=0.15.0&versions=0.15.1&versions=0.15.2&versions=0.8.3.post0&versions=0.12.1), there are something like 100 downloads per day of 0.8.3.post0, compared to something around 2000 each for modin 15.2 (latest version) and 12.1 (last version to support python 3.7). 0.8.3.post0 downloads took a steep decline starting around May 31, and the last time we looked at python 3.6 downloads may have been earlier than that.

@modin-project/modin-contributors @modin-project/modin-core @devin-petersohn @vnlitvinov any thoughts on maintaining support for python 3.6?

![Screen Shot 2022-08-29 at 5 18 06 PM](https://user-images.githubusercontent.com/10712109/187308758-6fe05a60-90a5-438c-9208-cffa44b009f3.png)

**Comment by mvashishtha** [comment]
@jbrockmendel:

@vnlitvinov, @devin-petersohn and I agreed offline that now that we already have python 3.6 support, we should do one release (supposed to come very soon) with it, then drop it. That way, if people want to use Modin on Python 3.6, they can use a much more up to date Modin version than 0.8.3, which is from January 2021. We will eventually add support using the same model for py37+pandas1.1, though.

**Comment by jbrockmendel** [comment]
Need to do some reading, wondering if we can make use of https://docs.python.org/3/library/multiprocessing.shared_memory.html once py38+

**Comment by pyrito** [comment]
@jbrockmendel what were you thinking of using shared memory for specifically?

**Comment by jbrockmendel** [comment]
daydreaming of a scenario in which we don't have to serialize/deserialize ndarrays

**Comment by vnlitvinov** [comment]
Ray Plasma already uses shared memory if running on a single node... Might be useful for MPI-backed [unidist](https://github.com/modin-project/unidist), though.
