### ISSUE TITLE
BUG: using modin objects captured from scope in dask remote functions raises `Exception: TypeError("object of type 'coroutine' has no len()")`

### ISSUE THREAD

**Issue by kareemamrr** [modin-project/modin#4919]
### System information
- **OS Platform and Distribution**: Zorin OS 16.1
- **Modin version**: 0.15.2
- **Python version**: 3.9.12
- **Code we can use to reproduce**:

**Note** you must have environment variable `MODIN_ENGINE=DASK`:

```py
import modin.pandas as pd

s1 = pd.Series([1])
s2 = pd.Series([2])

def f(x):
  return s2[0]

print(s1.apply(f))
```

### Describe the problem

When trying to apply a function element wise on a Pandas Series, it throws back `Exception: TypeError("object of type 'coroutine' has no len()")`. I reran the code using traditional Pandas and it worked fine.

### Source code / logs

The full traceback for the original reproducer (not the current one edited in) is available [here](https://gist.github.com/kareemamrr/5436c2e92ee16c5f75f9dbbb3c8ad5b4)

**Comment by pyrito** [comment]
@kareemamrr thanks for opening the issue! I'll take a look into it and see what's going on here.

This seems related to what some people saw here: https://github.com/modin-project/modin/issues/2498

@RehanSD could you please take a look?

**Comment by pyrito** [comment]
@mvashishtha could you please take a look at this issue?

**Comment by mvashishtha** [comment]
@kareemamrr thank you for reporting this issue. I was able to reproduce it with a short script that I edited into your original post. The bug seems to apply when a UDF uses a Modin object from the local scope. When the Dask worker initializes the Modin dataframe from its pickled form, we have two problems: (1) the worker is trying to initialize its own dask cluster (2) it seems `client.ncores()` is returning a coroutine instead of a dict as it normally does: https://github.com/modin-project/modin/blob/41e32e9edcd1e6755d6f959e573f807a75c7ae7e/modin/core/execution/dask/common/utils.py#L49

@kareemamrr To work around the bug, I would suggest either switching to Ray, or using a `groupby` instead of accessing the outer frame within `fill`. e.g. if you do the following

```python
import pandas

state_and_modes = df[['STATE', 'COUNTY']].groupby('STATE', as_index=False).agg(pandas.Series.mode)
df['STATE'].to_frame().merge(state_and_county, on='STATE', how='left')['COUNTY']
```

you can get a series with the most common county for each state.

cc @YarShev in case you have thoughts about how to deal with this, because I see you commented about a fix for a similar case in tests [here](https://github.com/modin-project/modin/issues/2498#issuecomment-745808956).
