### ISSUE TITLE
Slow when using numpy with modin and problems with JOIN

### ISSUE THREAD

**Issue by cnll0075** [modin-project/modin#494]
When applying simple transformations with numpy, for example, replacing empty entries by Nan using the following command:

data[i] = np.where(data[i]=='',np.nan,data[i])

takes 10* more time than native pandas. Wonder what is the reason and how can I improve it.

Another (unrelated) problem I've encountered, is error message like 'The task with ID 00000000d6a1d629907d4f5af63077dc108c27f1 is a driver task and so the object created by ray.put could not be reconstructed.' When I perform JOIN operation in the dataframe. How can I resolve it?

Thanks!

**Comment by devin-petersohn** [comment]
Hi @cnll0075 thanks for the questions.

> When applying simple transformations with numpy, for example, replacing empty entries by Nan using the following command:
> ...
> takes 10* more time than native pandas. Wonder what is the reason and how can I improve it.

The reason it is taking so long is that for numpy operations, we have to convert the Modin DataFrame into a numpy array. Doing so takes time because the DataFrame is partitioned for performance. Any time we have to convert the DataFrame to a numpy or pandas object, it is going from a distributed object to a single object. That is the overhead you are seeing.

For your particular command, you can try the `where` implementation. It has the same API and usage as pandas. You can try:

`data[i] = data[i].where(data[i] == "", np.nan)`

This may or may not be faster. Distributed `Series` is still under development, so operations that handle the Series one at a time or individually sometimes are slower.

>Another (unrelated) problem I've encountered, is error message like 'The task with ID 00000000d6a1d629907d4f5af63077dc108c27f1 is a driver task and so the object created by ray.put could not be reconstructed.' When I perform JOIN operation in the dataframe. How can I resolve it?

What version of Modin are you using and what is your operating system?

This error usually occurs when the system has run out of memory. If you are trying to use a large DataFrame, take a look at the out of core usage in the [documentation](https://modin.readthedocs.io/en/latest/out_of_core.html). It will allow you to use your disk as an overflow for memory.

**Comment by cnll0075** [comment]
Thanks a lot for your quick reply. OK I will try out the 'where' implementation.

Regarding the JOIN problem, my operating system is Linux and Modin 0.3.1.

I am pretty sure I didn't run out of the memory because I have finished the run using pandas (it was so slow that I wanted to use Modin). My system has 240 GB of memory and when the error occurred, the system still has about 120 GB of free memory. I indeed noticed that compared to Pandas, Modin takes up a lot of memory in cache, wonder if that's affecting anything.

                    total        used        free      shared  buff/cache   available
Mem:            240         124          24           0          90             114
Swap:             0           0           0

**Comment by devin-petersohn** [comment]
It could still be memory, because Modin is designed to only use up to 60% of the max memory available by default (pandas can use 100%), because we want Modin to work well with other applications that use a lot of memory. Out of core implementation will let you exceed your memory by using the disk also (most large scale systems also have this). 

Joins are memory intensive, are you seeing a `Defaulting to pandas` warning anywhere? For some classes of joins, we haven't optimized them in Modin yet.

**Comment by cnll0075** [comment]
I see. Can we change the maximum memory for Modin by MODIN_MEMORY?

I don't recall seeing that warning; maybe I missed it.

**Comment by devin-petersohn** [comment]
It should work to set maximum memory with `MODIN_MEMORY`, but it will only take an integer value right now. We haven't made it sophisticated enough to be able to accept `200GB` yet, you would have to  set `MODIN_MEMORY=200000000000`.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
