### ISSUE TITLE
Add support for Ray 2.0

### ISSUE THREAD

**Issue by kleecmt** [modin-project/modin#5072]
Ray 2.0.0 has been out. It will be great if modin supports it.

As of now, the poetry locking shows
```
   1: fact: modin (0.15.3) depends on modin (0.15.3)
   1: fact: modin (0.15.3) depends on pandas (1.4.4)
   1: fact: modin (0.15.3) depends on packaging (*)
   1: fact: modin (0.15.3) depends on numpy (>=1.18.5)
   1: fact: modin (0.15.3) depends on fsspec (*)
   1: fact: modin (0.15.3) depends on psutil (*)
   1: fact: modin (0.15.3) depends on ray (>=1.4.0,<1.13.0)
   1: fact: modin (0.15.3) depends on pyarrow (>=4.0.1)
   1: fact: modin (0.15.3) depends on redis (>=3.5.0,<4.0.0)
   1: fact: modin (0.15.3) depends on protobuf (<4.0.0)
```
Tho I can't find where are those requirements coming from.

**Comment by mvashishtha** [comment]
@kleecmt thank you for reporting this issue. For now you should be able to use ray 2.0.0 by installing Modin from the latest source, following the instructions here: https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch

The Modin contributors should release modin 0.16 very soon (hopefully within a week), and at that point you will be able to use Modin 0.16 with the latest version of ray.

> Tho I can't find where are those requirements coming from.

I think those come from [requirements-no-engine](https://github.com/modin-project/modin/blob/release-0.15.3/requirements/requirements-no-engine.yml) and [setup.py](https://github.com/modin-project/modin/blob/release-0.15.3/setup.py).

I'm going to close this issue for now because the latest Modin source does support Ray 2.0. Please watch out for Modin 0.16, and please comment here if you have any more questions.
