### ISSUE TITLE
DataFrame shallow copy acting deep

### ISSUE THREAD

**Issue by wuisawesome** [modin-project/modin#514]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OS X 10.13.6
- **Modin installed from (source or binary)**: pip 
- **Modin version**: 0.4.0
- **Python version**:  3.7.2
- **Exact command to reproduce**: Run the below script

### Describe the problem

Modin currently ignores the deep parameter for `df.copy()` and always deep copies.

### Source code / logs

```df = pd.DataFrame({'X': list(range(5)), 'Y': list(range(5))})
df2 = df.copy(deep=False)
df['X'][0]=99
assert df['X'][0] == df2['X'][0], "Should be true for a shallow copy"```

**Comment by wuisawesome** [comment]
I think that in order to fix this we just need QueryCompiler.copy() to take an option param `deep`. If deep is false then we shouldn't deep copy the constructor args.

**Comment by ipacheco-uy** [comment]
Hi @wuisawesome i try your idea, i add that option param and then in case it is False :

`return self.__constructor__(
        self.data, self.index, self.columns, self._dtype_cache
    )
`
instead of copy each of the constructor args, but it is still deep copying.

**Comment by devin-petersohn** [comment]
@wuisawesome, @ipacheco-uy The `__setitem__` issue is that the plasma store is immutable. We cannot update things inplace, and it is copying whenever we write some new data. We need to make sure that the references are propagated to the copies. We also enforce that `FrameManager` objects are immutable (and thus, `QueryCompiler` objects as well).

High level idea for how to implement this:

* All `DataFrame`s that are copies share a `QueryCompiler`. `df.copy()` will just return `DataFrame(query_compiler=self.query_compiler)`.
  * This will help with things like `df.index = [...]`, because no extra compute will be required. 
* When one `DataFrame` in the set has an `inplace` operation, we replace the `QueryCompiler` with the new one and propagate that new `QueryCompiler` to all of the other `DataFrame`s that depend on it. This should be fast because it is just updating the pointers.

**Comment by devin-petersohn** [comment]
@ipacheco-uy Is this an issue you are interested in trying to fix?
