### ISSUE TITLE
Binder build fails with HDF5 installation not found

### ISSUE THREAD

**Issue by eavidan** [modin-project/modin#519]
### Describe the problem

[Binder link](https://mybinder.org/v2/gh/modin-project/modin/master) fails with: "ERROR:: could not find a local HDF5 installation"

**Comment by devin-petersohn** [comment]
Thanks @eavidan, it is probably because of the `tables` in `requirements.txt`. We had this issue in travis temporarily when tables pushed an update, but it was fixed with a pin of the `tables` version to the previous version. Since binder is effectively building a docker image from the `requirements.txt`, this is likely the problem.

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
