### ISSUE TITLE
iloc fails with ValueError: cannot reindex from a duplicate axis

### ISSUE THREAD

**Issue by eavidan** [modin-project/modin#524]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.2
- **Modin installed from (source or binary)**: source
- **Modin version**: 0.4
- **Python version**: 3.6.7
- **Exact command to reproduce**:

### Describe the problem
When there are duplicate index `modin.dataframe.iloc` fails with `ValueError: cannot reindex from a duplicate axis` while `pandas` works

### Source code / logs
```py
# works
import pandas as pd

samples = pd.DataFrame({'A': [1, 2, 3], 'B': [3, 4, 5]}, index=[0, 0, 1])
samples.iloc[0]

#does not work
import modin.pandas as pd

samples = pd.DataFrame({'A': [1, 2, 3], 'B': [3, 4, 5]}, index=[0, 0, 1])
samples.iloc[0]
```

**Comment by devin-petersohn** [comment]
Thanks @eavidan, great find!

The Indexing methods (`loc`/`iloc`) need to be updated a bit. They work, but they can be slow in some situations, and given the new additions we have been working on we should make sure that this isn't killing performance. 

Since the whole module needs updating, I will take this as my next big undertaking after #522 is merged.
