### ISSUE TITLE
modin for all python?

### ISSUE THREAD

**Issue by kakaok** [modin-project/modin#559]
does modin can improve all python packages, if this can run for all packages it will wonderful for pythoner

**Comment by devin-petersohn** [comment]
Hi @kakaok, thanks for posting!

A lot of effort is being spent on the pandas API at the moment. We feel it is important that we deliver at least one component that works well, instead of partially implementing a number of functionalities.

Not all packages can benefit from parallelism and not all functionalities are easy to parallelize. If you're interested in trying to parallelize code that interacts with other libraries, I'd suggest looking at Ray: https://github.com/ray-project/ray. We make heavy use of Ray and it is the main engine that we develop on. There are some great tutorials, even if you have no parallel or distributed computing background: https://github.com/ray-project/tutorial

Let me know if you have any other questions!

**Comment by kakaok** [comment]
Hi @devin-petersohn ,thanks for answer!
