### ISSUE TITLE
unable to parse a column of json strings in modin dataframe (works in pandas)

### ISSUE THREAD

**Issue by ophiry** [modin-project/modin#616]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.4
- **Modin installed from (source or binary)**:pip
- **Modin version**:0.5.0
- **Python version**:3.7.3
- **Exact command to reproduce**:

```
import pandas
import modin.pandas
import json

pandas.DataFrame.from_dict({'a': ['{}']}).a.apply(json.loads)

```

> 0    {}
> Name: a, dtype: object
> 

`modin.pandas.DataFrame.from_dict({'a': ['{}']}).a.apply(json.loads)
`

> TypeError: the JSON object must be str, bytes or bytearray, not float

### Describe the problem
I have a dataframe of json strings I want to convert to json objects. df.col.apply(json.loads) works fine for pandas, but fails when using modin dataframes.

also posted in stackoverflow: https://stackoverflow.com/q/56096738/590335

**Comment by devin-petersohn** [comment]
Hi @ophiry, thanks for the report!

The error is coming from the error checking component of the run, where we call the `apply` (or `agg`) on an empty DataFrame to determine the return type and let pandas handle the error checking ([Link](https://github.com/modin-project/modin/blob/master/modin/pandas/series.py#L368-L372)).

Locally, I can reproduce this issue and have fixed it by changing the line to perform the operation on one line of the Series. This may affect the performance, so I need to do some more tuning to see if there is a way to speed it up and still be robust. After the fix the overhead of that check is ~10ms for 256 columns and I don't think we want error checking to take that long.

I will push a PR that fixes it for Series, since it is a small change. DataFrame will also need a similar update.
