### ISSUE TITLE
Lambda df.apply issues returning NaN on a column

### ISSUE THREAD

**Issue by ShauryaUppal-1Mg** [modin-project/modin#618]
### System information
MACOS: Python3
using modins latest version `pip install modin`

### Describe the problem

On a column df.apply is returning nan values. 

Check Images below:
![Screenshot 2019-05-13 at 9 53 42 PM](https://user-images.githubusercontent.com/47315683/57638085-a1ce3480-75ca-11e9-8702-401577c1559f.png)
![Screenshot 2019-05-13 at 9 53 17 PM](https://user-images.githubusercontent.com/47315683/57638101-ad216000-75ca-11e9-9877-326026ead85c.png)
![Screenshot 2019-05-13 at 9 52 46 PM](https://user-images.githubusercontent.com/47315683/57638111-b4486e00-75ca-11e9-8596-d59e86fcbe81.png)

**Comment by ShauryaUppal-1Mg** [comment]
On a single column, modin is giving nan values.

On pandas see the comparative result. Also, what is (pid = 20547) here?

**Comment by devin-petersohn** [comment]
Hi @ShauryaUppal-1Mg thanks for the report!

The behavior of printing the `nan`s is happening during error checking, and can be fixed at the same time as #616 because they are slightly related.

The values to the right of `pid=...` are the actual print values from the function. The tricky thing with `print` is that it has a side effect, writing to `stdout`. Because things are running in different processes, it can be challenging to get the order correct because multiple processes have to write to the driver's stdout. 

For general purpose `lambda` functions, it will work provided the function has no side effect.

**Comment by ShauryaUppal-1Mg** [comment]
Yes, Image 2 shows it works on a complete dataset but on a column we get nan values.

**Comment by devin-petersohn** [comment]
The issue looks like it is printing both `nan` and the correct values. The `nan`s are being printed during the error checking phase. It should be straight-forward to fix that.
