### ISSUE TITLE
Modin progress bar

### ISSUE THREAD

**Issue by yuanjie-ai** [modin-project/modin#629]
mdf['title'].apply(func)
modin can add a modin-process-bar

---
![image](https://user-images.githubusercontent.com/20265321/58155364-4d9c1200-7ca6-11e9-96ea-1670afdd72b1.png)

**Comment by devin-petersohn** [comment]
Hi @Jie-Yuan, thanks for the request.

Is this something you'd be interested in contributing? Typically a progress bar requires extra compute and will decrease overall performance. Some components of Modin are asynchronous, so we would have to change that to make it work properly.

Would a progress bar help with using Modin even though it will decrease performance?

**Comment by sunnyjiechao** [comment]
@devin-petersohn  a progress bar will be a useful function if it does for me.  I think a progress bar can be an option for users,  there may be two methods I can suggest:
1) built-in function 
`
from modin.pandas import tqdm
mdf['title'].tqdm(apply(func))
`
2) function params - (apply, map)
`
from modin.pandas import tqdm
mdf['title'].tqdm(func, tqdm=True)
`

i'm interested in contributing this new feature ~

**Comment by devin-petersohn** [comment]
@sunnyjiechao Thanks! For starters it should probably go in `modin.experimental.pandas`.

I think the best course of action would be to register a `tqdm` option to `modin.experimental.pandas.options`. That way you can enable globally like this:

```python
import modin.experimental.pandas as pd
pd.options.tqdm = True  # enable progress bar
...
pd.options.tqdm = False  # disable progress bar
...
```
I think it feels more pandas-like to add as an option rather than add a new API in that way. Plus if you want progress bar for multiple lines in a row it's just one addition.

I propose this get broken up into 2 pull requests. The first pull request is to add an option for `tqdm`. The second pull request can implement the progress bar. Do you think that makes sense @sunnyjiechao ?

Link to pandas options: https://github.com/pandas-dev/pandas/blob/master/pandas/_config/config.py

**Comment by sunnyjiechao** [comment]
Yes, I can't agree with you more, Your thoughts are very good that it looks more pandas-like.

**Comment by devin-petersohn** [comment]
I think all it will take is adding `pandas.core.config.register_option("tqdm", False)` to the __init__.py in `modin.experimental.pandas` ([Link to file](https://github.com/modin-project/modin/blob/master/modin/experimental/pandas/__init__.py)) to add the option.

It would be good to test it first though. After that PR, then it can be a check for the option flag to use the progress bar functionality.

**Comment by sunnyjiechao** [comment]
Got u, thanks

**Comment by sunnyjiechao** [comment]
@devin-petersohn So sorry for that, after working on it long time, i found it is very diffcult to figure it out and also not useful enough for wasting too compute resource, i have to say git it up.

I am willing try to contribute  more useful rather than fancy function of modin

**Comment by devin-petersohn** [comment]
No problem @Jie-Yuan, if you want to take a look at #658, there is a list of things there that can be implemented. Let me know!

**Comment by clgarciga** [comment]
I was just going to ask about this when I found https://github.com/modin-project/modin/pull/1589

**Comment by mvashishtha** [comment]
Now that we have a progress bar for some queries, I'm going to close this issue in favor of more specific progress bar feature requests, e.g. #2775 and #4167.
