### ISSUE TITLE
Feature Request: read_csv on compressed files

### ISSUE THREAD

**Issue by wangym1993** [modin-project/modin#630]
# Request for feature

Hi Modin Developers,

The original Pandas package's read_csv supports compressed files reading, which is a neat features for me to save Hard disk spaces..

It would be great to see modin.pandas.read_csv() will accept compressed files as well. 👍 

Thanks!

**Comment by devin-petersohn** [comment]
Hi @wangym1993, thanks for the request! I completely agree.

We had someone on the mailing list interested in working on this, I left some notes on that thread about how it could be done. Link: https://groups.google.com/forum/#!topic/modin-dev/fyYaZXWjp-o. It's been a few weeks so the author may not be working on it any more.

I will flag as Help Wanted because I don't think the addition will be that much overhead and we have a full backlog for this release. Let me know if you're interested in contributing it, I can help point you to the right places.

**Comment by devin-petersohn** [comment]
Added in #682
