### ISSUE TITLE
parallel read_sql example for dask

### ISSUE THREAD

**Issue by Harshitg** [modin-project/modin#846]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64Bit
- **Modin installed from (source or binary)**: source
- **Modin version**: 0.6.2
- **Python version**:3.7.2
- **Exact command to reproduce**: https://discuss.modin.org/t/experimental-api-initial-discussion/28

### Describe the problem
I am using the dask backend and it gives following error "AttributeError: module 'modin.data_management.factories' has no attribute 'ExperimentalPandasOnDaskFactory'". Should i try using ray. 

The release note mention usage of offset and limit, can someone please share a working example of the function?

### Source code / logs
```
def modin_test():
    pd.read_sql(
        sql=TBL_NAME,
        con=CONN,
        partition_column="col0",
        lower_bound=0,
        upper_bound=NUM_ROWS-1
    )
```

**Comment by devin-petersohn** [comment]
Hi @Harshitg, thanks for posting!

We don't yet have `read_sql` for the vanilla dask backend, but we are working toward it with #754. It doesn't currently work with the experimental API because it doesn't have an implementation in the non-experimental version yet. Thanks again for posting, I'll add this to feature requests, but it will be a part of the follow-on to #754.

**Comment by devin-petersohn** [comment]
`read_sql` was added to the Dask backend, feel free to re-open this issue if it was not resolved.
