### ISSUE TITLE
merging two pandas data frames with modin.pandas gives ValueError

### ISSUE THREAD

**Issue by boris-ctcue** [modin-project/modin#872]
### System information
- **Macos Mojave 10.14.6 **:
- **Modin installed from source with pip install modin**:
- **Modin latest (0.6.3)**:
- **python version : 3.6**:
- **pd.merge**:

### Problem
In an attempt to make my pandas code faster I installed modin and tried to use it. A merge of two data frames that had previously worked gave me the following error:

ValueError: can not merge DataFrame with instance of type <class 'pandas.core.frame.DataFrame'>

Here is the info of both data frames:

printing event_df.info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1980101 entries, 0 to 1980100
Data columns (total 5 columns):
other_id     object
id             object
category       object
description    object
date           datetime64[ns]
dtypes: datetime64[ns](1), object(4)
memory usage: 75.5+ MB

printing other_df info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 752438 entries, 0 to 752437
Data columns (total 4 columns):
id            752438 non-null object
other_id    752438 non-null object
Value     752438 non-null object
Unit      752438 non-null object
dtypes: object(4)
memory usage: 23.0+ MB
Here are some rows from event_df:

other_id            id     category      description        date
08E5A973        1  some_string      some_string     2019-04-09 
17B71019E       4  some_string      some_string      2019-11-08 
17B71019E1     7  some_string      some_string      2019-11-08 
and here are 3 rows from other_df:

id                             other_id                                                          Value      Unit
a01  BE4F15A3AE8A508ACB45F0FC8CDC173D1628D283         3  some_string
a02  BE4F15A3AE8A508ACB45F0FC8CDC173D1628D283         3  some_string
a03  BE4F15A3AE8A508ACB45F0FC8CDC173D1628D283         3  some_string
I tried installing the version cited in this question Join two modin.pandas.DataFrame(s), but it didn't help.

Here's the line of code throwing the error:

joint_dataframe2 = pd.merge(event_df,other_df, on = ["id","other_id"])

It seems there is some problem with modin's merge functionality. Is there any workaround such as using pandas for the merge and using modin for a groupby.transform()? I tried overwriting the pandas import after the merge with import modin.pandas, but got an error saying pandas was referenced before assignment. Has anyone come across this problem and if so, is there a solution?

Here's the traceback: 

Traceback (most recent call last):
  File "train_model.py", line 187, in <module>
    data.populate_events()
  File "/Users/x/src/generator/generator/y/y/readers/reader", line 377, in populate_events
    joint_dataframe2 = pd.merge(event_df,other_df, on = ["other_id","id"])
  File "/Users/x/miniconda3/lib/python3.6/site-packages/modin/pandas/general.py", line 77, in merge
    "can not merge DataFrame with instance of type {}".format(type(right))
ValueError: can not merge DataFrame with instance of type <class 'pandas.core.frame.DataFrame'>

Any help would be much appreciated

**Comment by devin-petersohn** [comment]
Hi @boris-ctcue, thanks for posting!

What were the operations that you ran before this? Are you trying to operate using both Modin and pandas at the same time? If this is a Jupyter Notebook or ipython or python interpreter, you may need to restart the kernel. We don't expect users to try to integrate Modin into a _running_ instance, rather it is a drop-in replacement. If this wasn't the case, I would like to know what you ran in Modin to get a pandas DataFrame out because that would be a bug.

The `merge` functionality is expecting a Modin dataframe, but it is getting a pandas dataframe. That is the error that is getting thrown. To turn a pandas DataFrame into a Modin DataFrame, you can just pass the pandas DataFrame to the constructor:

```python
import modin.pandas as pd

pandas_df = ...
df = pd.DataFrame(pandas_df)
```

After this it should fix the issue. Note that this will distribute the dataframe and may take some time if the dataframe is very large.

**Comment by boris-ctcue** [comment]
Hi @devin-petersohn, you were right, the data frames were being created as core pandas object, so I was able to solve the problem by re-instantiating them as you suggested. However, I ran into an error wile calling the following groupby and apply:

data_frame1 = data_frame1.groupby('d').apply(self.get_previous_and_following_categories)

here is the UDF:

def get_previous_and_following_categories(self,group):
		group['previous_category'] = group['category'].shift()
		group['following_category'] = group['category'].shift(-1)
		return group

Here is the error:

    f(self, obj) # Call unbound method with explicit self
  File "/Users/borismetodiev/miniconda3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py", line 837, in save_file
    raise pickle.PicklingError("Cannot pickle closed files")
pickle.PicklingError: Cannot pickle closed files

Is modin capable of running groupies followed by UDFs?

**Comment by devin-petersohn** [comment]
>Is modin capable of running groupies followed by UDFs?

Yes, but you may need to restructure this specific call a little bit because of the way that cloudpickle handles `self.some_function`. Cloudpickle is a dependency of Ray and Dask, so using either of those will likely result in the same issue. Since you aren't using `self` in the UDF, it should be possible to define that function outside of the context of the class.

If you don't mind, would you open this as a new issue for indexing/tracking? It doesn't appear related to the above issue in the first comment. Thanks!

**Comment by devin-petersohn** [comment]
@boris-ctcue I am going to close this issue as the original issue was resolved.

If you still have problems with the UDF, please open a new issue to be tracked. Thanks!
