### ISSUE TITLE
Need an example to show the performance advantage of modin

### ISSUE THREAD

**Issue by hhbyyh** [modin-project/modin#893]
Modin looks really promising and I'm evaluating it for production usage. Thanks for working on it.

I used jupyter notebook to benchmark modin against pandas but cannot find any performance improvement. And for many of the operations modin spent much more wall clock time than standard Pandas on a single node.

If possible, can you please refer or provide some example that shows the performance advantage of Modin, which I guess is the primary reason for users to use Modin. Thanks.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac pro
- **Modin installed from (source or binary)**: pip
- **Modin version**: 0.6.3
- **Python version**: 3.6
- **Exact command to reproduce**: basically all the pandas operation.

**Comment by hhbyyh** [comment]
cc @devin-petersohn Appreciate your help.

**Comment by devin-petersohn** [comment]
Hi @hhbyyh, would you provide the code you used for your example? I would like to understand the use-case you are testing. Historically when this happens, people are often using synthetic datasets that don't conform to typical real-world workflows, which is why I ask (e.g. doing all operations with only a single column of numeric data).

Typically, our benchmark dataset is the commonly used NYC taxi dataset: https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page

For out-of-core, we have tested a full year (250GB). For in-memory, we usually test a single month (~1.5GB - 2.5GB).: 

A representative workflow would be to run:

```
read_csv
count
isna
groupby(by="passengers").count()
sort_values
transpose
```

Some of the way we shuffle data between workers isn't optimized yet, but there is ongoing work to improve it: https://github.com/modin-project/modin/pull/725

**Comment by hhbyyh** [comment]
Thanks for the response.
I uploaded my notebook to https://github.com/hhbyyh/ray_test/blob/master/modin_test.ipynb 

I still think it would be very helpful to prepare a notebook example that can demo the advantage and applicable scenarios of Modin. I will try NYC dataset and if it's OK with you, I can probably compose a PR with the notebook.

**Comment by hhbyyh** [comment]
No luck with the NYC taxi data. https://github.com/hhbyyh/ray_test/blob/master/modin_test_nyc.ipynb. Let me know if there's anything I did wrong.

**Comment by devin-petersohn** [comment]
> No luck with the NYC taxi data.
I see several times in the notebook presented where Modin outperforms, so I wouldn't call it no luck 😄 . There are a lot of low-level details and drilling down that could be done on every number, but for now I will mention some high level points.

- The defaulting to pandas performance speaks for itself.
- The performance of `sort_values` is what I was referring to about the shuffle cost in my previous comment. We are working on this - #725.
- Try `groupby.count` instead of `groupby.mean`. We recently updated how we do `groupby` and haven't had the time to propagate all of these updates to all `groupby` operators.
- `compute` on a Dask dataframe creates a pandas DataFrame so all operations on the `dask_csv_data` are on a `pandas.DataFrame`. You want to use `persist` and you will need to call it for every operation.
- `modin_csv_data[modin_csv_data.apply(lambda x: x['tip_amount'] > x['fare_amount'], axis=1)]` this is a very inefficient way to write `modin_csv_data[modin_csv_data["tip_amount"] > modin_csv_data["fare_amount"]]`. It is very inefficient in both pandas and modin (and probably dask but I do not know for sure). `apply` is something that is very difficult to optimize because valid UDFs are nearly unbounded in nature, so we can only rely on simple parallelism for this case. 
- The 2019-1 is ~600MB, but I was suggesting in the 1.5-2.5GB range, e.g. 2014-1. 

Let me know if this helps!

**Comment by hhbyyh** [comment]
Thanks for the response. I'll try the suggestions today. Meanwhile, the only place that modin outperforms is read_csv as far as I see. And read_csv in modin is not that stable. Sometimes it's much longer than pandas.

**Comment by devin-petersohn** [comment]
>Meanwhile, the only place that modin outperforms is read_csv as far as I see. And read_csv in modin is not that stable. Sometimes it's much longer than pandas.

If you have a question about the performance I'm happy to answer, but please don't come to the repo to spread unhelpful negativity. If you have some constructive and actionable statement about the project, I'm happy to hear it. If you want to understand some things about the performance, I'm also happy to answer any questions.  If you'd like to contribute to the success of the project and make it work better for your use cases, I'm happy to point you in the direction where you can contribute.

You have only tested ~2% of the pandas API and have made a blanket statement about the performance. This seems a bit presumptuous and not really fair to the people who work hard on this project. In my previous comment there was a list of operations you could do to get a representative set of what we have implemented so far, some that could use improvement, but most are faster than pandas. If you would like a representative set of operations please revisit that comment and use those operations instead.

If I look closely at the cells in your first notebook, I can see that after the run you went back and re-ran the `read_csv` cells. Prior this point, Ray probably was at the memory limit of the Plasma store and started evicting objects. Was the time for Modin better or worse the first time around? Did the machine have enough memory to run 3x the dataset? Remember that pandas copies a lot for each operation and you need ~5-10x the memory for the dataset for each of pandas, Dask, and Modin. It's usually best to do a clean run of each of these separately if you want to be scientific about it.

Because there is no action to be taken, I am closing this issue.

**Comment by hhbyyh** [comment]
I don't mean to offend or anything. Sorry if there's any misunderstanding. 

All I'm trying to do is to find the applicable scenarios of Modin and maybe compose a notebook to demo it to others. Thank you and other contributors who have worked hard on the project and I do think it can help in many cases.

If you have a benchmark notebook that can demo the speedup from Modin, I think that would be very valuable to all the users so they won't need to try things in the wrong direction like I did. If you don't have one, I'm more than happy to help you create one. I understand Pandas has a very large set of API and there's a lot of work to do, but we need to tell users which operations, under which circumstance (data, memory, cores, hard drive) is already working great, and I think the best way is to present a notebook for that.

Thank you for your comments and suggestions. I'll take my notebook off Github just in case it's misleading other users.
