### ISSUE TITLE
How to Convert  modin.pandas.DataFrame to pandas.DataFrame 

### ISSUE THREAD

**Issue by yuanjie-ai** [modin-project/modin#896]
How to Convert  modin.pandas.DataFrame to pandas.DataFrame

**Comment by eavidan** [comment]
This is not part of the API as pandas.DataFrame, naturally, does not posses such a method.
You can use the private method `DataFrame._to_pandas()` to do this conversion.
If you would like to do this through the official API you can always save the Modin DataFrame to storage (csv, hdf, sql, ect) and then read it back using Pandas. This will probably be the safer way when working big DataFrames, to avoid out of memory issues.

**Comment by Jie-Yuan** [comment]
Thanks!

**Comment by Vaderv** [comment]
how about reading a data frame into a modin data frame ?

**Comment by devin-petersohn** [comment]
@Vaderv if you have a `pandas.DataFrame` object, you can call Modin DataFrame constructor and it will be handled for you:

```python
import pandas
import modin.pandas as pd

# have a pandas.DataFrame object called `pandas_df`
modin_df = pd.DataFrame(pandas_df)
``` 

It is as easy as that 😄

**Comment by GHCamille** [comment]
@devin-petersohn actually when I do what you suggest I get a "(<class 'AttributeError'>, AttributeError("module 'modin' has no attribute 'DataFrame'"), <traceback object at 0x7fd3f3560100>)", is it deprecated ?

**Comment by bdklahn** [comment]
Ummm, @devin-petersohn, aren't you answering the opposite question?

I guess it is not part of the pandas API. Very weird. . . . The logical df2 = pandas.DataFrame(df1) doesn't work as would be expected (copy constructor pattern). (I understand that .copy() can be used)

I just wanted to simply test if the following is also broken in pandas. Maybe it is, since that is *supposed* to be the fallback.
(I guess I'll have to do something like pandas.read_csv(. . . nrows=9), to test)

In [437]: type(df2)
Out[437]: modin.pandas.dataframe.DataFrame

In [438]: category_hdrs[:9]
Out[438]: ['A1_1', 'A1_2', 'A1_3', 'A1_4', 'A1_5', 'A2b', 'A3', 'A3b', 'B2b']
\# a proper subset of all columns

In [439]: df2.dtypes[:9]
Out[439]: 
StartDatetime    datetime64[ns]
EndDatetime      datetime64[ns]
A1_1                    float64
A1_2                    float64
A1_3                    float64
A1_4                    float64
A1_5                    float64
A2                      float64
A2b                     float64
dtype: object

In [440]: df2[category_hdrs] = df2[category_hdrs].astype('category')
UserWarning: `DataFrame.setitem_unhashable_key` defaulting to pandas implementation.
UserWarning: Distributing <class 'pandas.core.frame.DataFrame'> object. This may take some time.

In [441]: df2.dtypes[:9]
Out[441]: 
StartDatetime    datetime64[ns]
EndDatetime      datetime64[ns]
A1_1                    float64
A1_2                    float64
A1_3                    float64
A1_4                    float64
A1_5                    float64
A2                      float64
A2b                     float64
dtype: object

**Comment by bdklahn** [comment]
Maybe modin is using an older pandas version?
In [444]: modin.__version__
Out[444]: '0.9.1'

In [445]: pandas.__version__
Out[445]: '1.2.3'

Anyway, .apply(lambda . . . ) also is not apparently implemented, either. So . . . simple basic things . . . not possible.

**Comment by devin-petersohn** [comment]
@bdklahn Please review our code of conduct and make sure any future messages follow it: https://github.com/modin-project/modin/blob/master/CODE_OF_CONDUCT.md. Comments should be respectful and constructive.

The comment by @eavidan above answers the question. If you follow the entire thread, my comment is answering a follow-up question. 

If you are running into an issue, please open a new issue. It more helpful to others looking for answers to questions to create another issue. `apply` is implemented, so please open a new issue if you have run into some problem. We also accept external contributions, and I'm happy to point you to the code where you can contribute a fix.

**Comment by bdklahn** [comment]
@devin-petersohn , Sorry about that. I edited my comment accordingly.
I agree with the practice of opening a new issue, and I probably should have done that. Sorry about that, too. I also should have more carefully read the comment by @Vaderv, to note it should be a treated as separate issue.
It's probably best not to actively encourage that by answering questions about an unrelated issue, in this issue's thread. It can be confusing for people, and make it hard to track everything which needs to be addressed relative to a repo.
Here's to hoping you will be "Gracefully accepting constructive criticism". :-)
[https://github.com/modin-project/modin/blob/master/CODE_OF_CONDUCT.md](https://github.com/modin-project/modin/blob/master/CODE_OF_CONDUCT.md)
